// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: example/simple/simple.proto

package simple

import (
	_ "github.com/kei2100/protoc-gen-marshal-zap"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SecretMessage string `protobuf:"bytes,2,opt,name=secret_message,json=secretMessage,proto3" json:"secret_message,omitempty"`
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_simple_simple_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_simple_simple_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_example_simple_simple_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SimpleMessage) GetSecretMessage() string {
	if x != nil {
		return x.SecretMessage
	}
	return ""
}

var File_example_simple_simple_proto protoreflect.FileDescriptor

var file_example_simple_simple_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x1a, 0x11, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x2d, 0x7a,
	0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0d, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0x88, 0xb5, 0x18,
	0x01, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x65, 0x69, 0x32, 0x31, 0x30, 0x30, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x2d, 0x7a, 0x61, 0x70, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_simple_simple_proto_rawDescOnce sync.Once
	file_example_simple_simple_proto_rawDescData = file_example_simple_simple_proto_rawDesc
)

func file_example_simple_simple_proto_rawDescGZIP() []byte {
	file_example_simple_simple_proto_rawDescOnce.Do(func() {
		file_example_simple_simple_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_simple_simple_proto_rawDescData)
	})
	return file_example_simple_simple_proto_rawDescData
}

var file_example_simple_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_simple_simple_proto_goTypes = []interface{}{
	(*SimpleMessage)(nil), // 0: simple.SimpleMessage
}
var file_example_simple_simple_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_simple_simple_proto_init() }
func file_example_simple_simple_proto_init() {
	if File_example_simple_simple_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_simple_simple_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_simple_simple_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_simple_simple_proto_goTypes,
		DependencyIndexes: file_example_simple_simple_proto_depIdxs,
		MessageInfos:      file_example_simple_simple_proto_msgTypes,
	}.Build()
	File_example_simple_simple_proto = out.File
	file_example_simple_simple_proto_rawDesc = nil
	file_example_simple_simple_proto_goTypes = nil
	file_example_simple_simple_proto_depIdxs = nil
}
