// Code generated by protoc-gen-marshal-zap. DO NOT EDIT.
// source: simple.pb.go

package simple

import (
	"go.uber.org/zap/zapcore"
	"strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = zapcore.NewNopCore
var _ = strconv.FormatInt

func (m *SimpleMessage) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if m == nil {
		return nil
	}

	enc.AddString("message", m.Message)

	enc.AddString("secret_message", "[MASKED]")

	return nil
}
