// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: test/proto2types/types.proto

package proto2types

import (
	_ "github.com/kei2100/protoc-gen-marshal-zap"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumerations
// https://developers.google.com/protocol-buffers/docs/proto#enum
type Types_Enum int32

const (
	Types_ENUM_0 Types_Enum = 0
	Types_ENUM_1 Types_Enum = 1
	Types_ENUM_2 Types_Enum = 2
)

// Enum value maps for Types_Enum.
var (
	Types_Enum_name = map[int32]string{
		0: "ENUM_0",
		1: "ENUM_1",
		2: "ENUM_2",
	}
	Types_Enum_value = map[string]int32{
		"ENUM_0": 0,
		"ENUM_1": 1,
		"ENUM_2": 2,
	}
)

func (x Types_Enum) Enum() *Types_Enum {
	p := new(Types_Enum)
	*p = x
	return p
}

func (x Types_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Types_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto2types_types_proto_enumTypes[0].Descriptor()
}

func (Types_Enum) Type() protoreflect.EnumType {
	return &file_test_proto2types_types_proto_enumTypes[0]
}

func (x Types_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Types_Enum) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Types_Enum(num)
	return nil
}

// Deprecated: Use Types_Enum.Descriptor instead.
func (Types_Enum) EnumDescriptor() ([]byte, []int) {
	return file_test_proto2types_types_proto_rawDescGZIP(), []int{0, 0}
}

type Types struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SecretVal  *string                `protobuf:"bytes,1,req,name=secret_val,json=secretVal" json:"secret_val,omitempty"`
	SecretVal2 *string                `protobuf:"bytes,41,req,name=secret_val2,json=secretVal2" json:"secret_val2,omitempty"`
	// Scalar Value Types
	// https://developers.google.com/protocol-buffers/docs/proto#scalar
	DoubleVal   *float64    `protobuf:"fixed64,2,req,name=double_val,json=doubleVal" json:"double_val,omitempty"`
	FloatVal    *float32    `protobuf:"fixed32,3,req,name=float_val,json=floatVal" json:"float_val,omitempty"`
	Int32Val    *int32      `protobuf:"varint,4,req,name=int32_val,json=int32Val" json:"int32_val,omitempty"`
	Int64Val    *int64      `protobuf:"varint,5,req,name=int64_val,json=int64Val" json:"int64_val,omitempty"`
	Uint32Val   *uint32     `protobuf:"varint,6,req,name=uint32_val,json=uint32Val" json:"uint32_val,omitempty"`
	Uint64Val   *uint64     `protobuf:"varint,7,req,name=uint64_val,json=uint64Val" json:"uint64_val,omitempty"`
	Sint32Val   *int32      `protobuf:"zigzag32,8,req,name=sint32_val,json=sint32Val" json:"sint32_val,omitempty"`
	Sint64Val   *int64      `protobuf:"zigzag64,9,req,name=sint64_val,json=sint64Val" json:"sint64_val,omitempty"`
	Fixed32Val  *uint32     `protobuf:"fixed32,10,req,name=fixed32_val,json=fixed32Val" json:"fixed32_val,omitempty"`
	Fixed64Val  *uint64     `protobuf:"fixed64,11,req,name=fixed64_val,json=fixed64Val" json:"fixed64_val,omitempty"`
	Sfixed32Val *int32      `protobuf:"fixed32,12,req,name=sfixed32_val,json=sfixed32Val" json:"sfixed32_val,omitempty"`
	Sfixed64Val *int64      `protobuf:"fixed64,13,req,name=sfixed64_val,json=sfixed64Val" json:"sfixed64_val,omitempty"`
	BoolVal     *bool       `protobuf:"varint,14,req,name=bool_val,json=boolVal" json:"bool_val,omitempty"`
	StringVal   *string     `protobuf:"bytes,15,req,name=string_val,json=stringVal" json:"string_val,omitempty"`
	BytesVal    []byte      `protobuf:"bytes,16,req,name=bytes_val,json=bytesVal" json:"bytes_val,omitempty"`
	EnumVal     *Types_Enum `protobuf:"varint,17,req,name=enum_val,json=enumVal,enum=proto2types.Types_Enum" json:"enum_val,omitempty"`
	// Other Message Types
	// https://developers.google.com/protocol-buffers/docs/proto#other
	OtherTypeVal           *OtherType1            `protobuf:"bytes,18,req,name=other_type_val,json=otherTypeVal" json:"other_type_val,omitempty"`
	NestedTypeVal          *Types_NestedType      `protobuf:"bytes,19,req,name=nested_type_val,json=nestedTypeVal" json:"nested_type_val,omitempty"`
	OtherTypeNestedTypeVal *OtherType2_NestedType `protobuf:"bytes,20,req,name=other_type_nested_type_val,json=otherTypeNestedTypeVal" json:"other_type_nested_type_val,omitempty"`
	// Oneof
	// https://developers.google.com/protocol-buffers/docs/proto#oneof
	//
	// Types that are valid to be assigned to OneofVal:
	//
	//	*Types_OneofStringVal
	//	*Types_OneofInt64Val
	//	*Types_OneofBoolVal
	OneofVal isTypes_OneofVal `protobuf_oneof:"oneof_val"`
	// Maps
	// https://developers.google.com/protocol-buffers/docs/proto#updating
	MapVal1     map[string]string      `protobuf:"bytes,24,rep,name=map_val1,json=mapVal1" json:"map_val1,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapVal2     map[string]*OtherType1 `protobuf:"bytes,25,rep,name=map_val2,json=mapVal2" json:"map_val2,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapEmptyVal map[string]string      `protobuf:"bytes,26,rep,name=map_empty_val,json=mapEmptyVal" json:"map_empty_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Repeated
	// * Repeated Scalar Values
	// * Repeated Enumerations
	// * Repeated MessageTypes
	// * (Repeated Maps -> NOT supported)
	// * (Repeated Repeated -> NOT supported)
	RepeatedVal1     []string      `protobuf:"bytes,27,rep,name=repeated_val1,json=repeatedVal1" json:"repeated_val1,omitempty"`
	RepeatedVal2     []Types_Enum  `protobuf:"varint,28,rep,name=repeated_val2,json=repeatedVal2,enum=proto2types.Types_Enum" json:"repeated_val2,omitempty"`
	RepeatedVal3     []*OtherType1 `protobuf:"bytes,29,rep,name=repeated_val3,json=repeatedVal3" json:"repeated_val3,omitempty"`
	RepeatedEmptyVal []string      `protobuf:"bytes,30,rep,name=repeated_empty_val,json=repeatedEmptyVal" json:"repeated_empty_val,omitempty"`
	// TODO wellknown types
	// https://developers.google.com/protocol-buffers/docs/reference/google.protobuf
	StructVal *structpb.Struct `protobuf:"bytes,31,req,name=struct_val,json=structVal" json:"struct_val,omitempty"`
	// Camelcasing
	XString *string `protobuf:"bytes,32,req,name=_String,json=String" json:"_String,omitempty"`
	// Handle Explicit Presence
	// https://protobuf.dev/programming-guides/field_presence/#presence-in-proto3-apis
	OptionalVal               *string     `protobuf:"bytes,33,opt,name=optional_val,json=optionalVal" json:"optional_val,omitempty"`
	OptionalNotPresentVal     *string     `protobuf:"bytes,34,opt,name=optional_not_present_val,json=optionalNotPresentVal" json:"optional_not_present_val,omitempty"`
	OptionalEnum              *Types_Enum `protobuf:"varint,35,opt,name=optional_enum,json=optionalEnum,enum=proto2types.Types_Enum" json:"optional_enum,omitempty"`
	OptionalNotPresentEnum    *Types_Enum `protobuf:"varint,36,opt,name=optional_not_present_enum,json=optionalNotPresentEnum,enum=proto2types.Types_Enum" json:"optional_not_present_enum,omitempty"`
	OptionalMessage           *OtherType3 `protobuf:"bytes,37,opt,name=optional_message,json=optionalMessage" json:"optional_message,omitempty"`
	OptionalNotPresentMessage *OtherType3 `protobuf:"bytes,38,opt,name=optional_not_present_message,json=optionalNotPresentMessage" json:"optional_not_present_message,omitempty"`
	PresentMessage            *OtherType3 `protobuf:"bytes,39,req,name=present_message,json=presentMessage" json:"present_message,omitempty"`
	NotPresentMessage         *OtherType3 `protobuf:"bytes,40,req,name=not_present_message,json=notPresentMessage" json:"not_present_message,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Types) Reset() {
	*x = Types{}
	mi := &file_test_proto2types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Types) ProtoMessage() {}

func (x *Types) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto2types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Types.ProtoReflect.Descriptor instead.
func (*Types) Descriptor() ([]byte, []int) {
	return file_test_proto2types_types_proto_rawDescGZIP(), []int{0}
}

func (x *Types) GetSecretVal() string {
	if x != nil && x.SecretVal != nil {
		return *x.SecretVal
	}
	return ""
}

func (x *Types) GetSecretVal2() string {
	if x != nil && x.SecretVal2 != nil {
		return *x.SecretVal2
	}
	return ""
}

func (x *Types) GetDoubleVal() float64 {
	if x != nil && x.DoubleVal != nil {
		return *x.DoubleVal
	}
	return 0
}

func (x *Types) GetFloatVal() float32 {
	if x != nil && x.FloatVal != nil {
		return *x.FloatVal
	}
	return 0
}

func (x *Types) GetInt32Val() int32 {
	if x != nil && x.Int32Val != nil {
		return *x.Int32Val
	}
	return 0
}

func (x *Types) GetInt64Val() int64 {
	if x != nil && x.Int64Val != nil {
		return *x.Int64Val
	}
	return 0
}

func (x *Types) GetUint32Val() uint32 {
	if x != nil && x.Uint32Val != nil {
		return *x.Uint32Val
	}
	return 0
}

func (x *Types) GetUint64Val() uint64 {
	if x != nil && x.Uint64Val != nil {
		return *x.Uint64Val
	}
	return 0
}

func (x *Types) GetSint32Val() int32 {
	if x != nil && x.Sint32Val != nil {
		return *x.Sint32Val
	}
	return 0
}

func (x *Types) GetSint64Val() int64 {
	if x != nil && x.Sint64Val != nil {
		return *x.Sint64Val
	}
	return 0
}

func (x *Types) GetFixed32Val() uint32 {
	if x != nil && x.Fixed32Val != nil {
		return *x.Fixed32Val
	}
	return 0
}

func (x *Types) GetFixed64Val() uint64 {
	if x != nil && x.Fixed64Val != nil {
		return *x.Fixed64Val
	}
	return 0
}

func (x *Types) GetSfixed32Val() int32 {
	if x != nil && x.Sfixed32Val != nil {
		return *x.Sfixed32Val
	}
	return 0
}

func (x *Types) GetSfixed64Val() int64 {
	if x != nil && x.Sfixed64Val != nil {
		return *x.Sfixed64Val
	}
	return 0
}

func (x *Types) GetBoolVal() bool {
	if x != nil && x.BoolVal != nil {
		return *x.BoolVal
	}
	return false
}

func (x *Types) GetStringVal() string {
	if x != nil && x.StringVal != nil {
		return *x.StringVal
	}
	return ""
}

func (x *Types) GetBytesVal() []byte {
	if x != nil {
		return x.BytesVal
	}
	return nil
}

func (x *Types) GetEnumVal() Types_Enum {
	if x != nil && x.EnumVal != nil {
		return *x.EnumVal
	}
	return Types_ENUM_0
}

func (x *Types) GetOtherTypeVal() *OtherType1 {
	if x != nil {
		return x.OtherTypeVal
	}
	return nil
}

func (x *Types) GetNestedTypeVal() *Types_NestedType {
	if x != nil {
		return x.NestedTypeVal
	}
	return nil
}

func (x *Types) GetOtherTypeNestedTypeVal() *OtherType2_NestedType {
	if x != nil {
		return x.OtherTypeNestedTypeVal
	}
	return nil
}

func (x *Types) GetOneofVal() isTypes_OneofVal {
	if x != nil {
		return x.OneofVal
	}
	return nil
}

func (x *Types) GetOneofStringVal() string {
	if x != nil {
		if x, ok := x.OneofVal.(*Types_OneofStringVal); ok {
			return x.OneofStringVal
		}
	}
	return ""
}

func (x *Types) GetOneofInt64Val() int64 {
	if x != nil {
		if x, ok := x.OneofVal.(*Types_OneofInt64Val); ok {
			return x.OneofInt64Val
		}
	}
	return 0
}

func (x *Types) GetOneofBoolVal() bool {
	if x != nil {
		if x, ok := x.OneofVal.(*Types_OneofBoolVal); ok {
			return x.OneofBoolVal
		}
	}
	return false
}

func (x *Types) GetMapVal1() map[string]string {
	if x != nil {
		return x.MapVal1
	}
	return nil
}

func (x *Types) GetMapVal2() map[string]*OtherType1 {
	if x != nil {
		return x.MapVal2
	}
	return nil
}

func (x *Types) GetMapEmptyVal() map[string]string {
	if x != nil {
		return x.MapEmptyVal
	}
	return nil
}

func (x *Types) GetRepeatedVal1() []string {
	if x != nil {
		return x.RepeatedVal1
	}
	return nil
}

func (x *Types) GetRepeatedVal2() []Types_Enum {
	if x != nil {
		return x.RepeatedVal2
	}
	return nil
}

func (x *Types) GetRepeatedVal3() []*OtherType1 {
	if x != nil {
		return x.RepeatedVal3
	}
	return nil
}

func (x *Types) GetRepeatedEmptyVal() []string {
	if x != nil {
		return x.RepeatedEmptyVal
	}
	return nil
}

func (x *Types) GetStructVal() *structpb.Struct {
	if x != nil {
		return x.StructVal
	}
	return nil
}

func (x *Types) GetXString() string {
	if x != nil && x.XString != nil {
		return *x.XString
	}
	return ""
}

func (x *Types) GetOptionalVal() string {
	if x != nil && x.OptionalVal != nil {
		return *x.OptionalVal
	}
	return ""
}

func (x *Types) GetOptionalNotPresentVal() string {
	if x != nil && x.OptionalNotPresentVal != nil {
		return *x.OptionalNotPresentVal
	}
	return ""
}

func (x *Types) GetOptionalEnum() Types_Enum {
	if x != nil && x.OptionalEnum != nil {
		return *x.OptionalEnum
	}
	return Types_ENUM_0
}

func (x *Types) GetOptionalNotPresentEnum() Types_Enum {
	if x != nil && x.OptionalNotPresentEnum != nil {
		return *x.OptionalNotPresentEnum
	}
	return Types_ENUM_0
}

func (x *Types) GetOptionalMessage() *OtherType3 {
	if x != nil {
		return x.OptionalMessage
	}
	return nil
}

func (x *Types) GetOptionalNotPresentMessage() *OtherType3 {
	if x != nil {
		return x.OptionalNotPresentMessage
	}
	return nil
}

func (x *Types) GetPresentMessage() *OtherType3 {
	if x != nil {
		return x.PresentMessage
	}
	return nil
}

func (x *Types) GetNotPresentMessage() *OtherType3 {
	if x != nil {
		return x.NotPresentMessage
	}
	return nil
}

type isTypes_OneofVal interface {
	isTypes_OneofVal()
}

type Types_OneofStringVal struct {
	OneofStringVal string `protobuf:"bytes,21,opt,name=oneof_string_val,json=oneofStringVal,oneof"`
}

type Types_OneofInt64Val struct {
	OneofInt64Val int64 `protobuf:"varint,22,opt,name=oneof_int64_val,json=oneofInt64Val,oneof"`
}

type Types_OneofBoolVal struct {
	OneofBoolVal bool `protobuf:"varint,23,opt,name=oneof_bool_val,json=oneofBoolVal,oneof"`
}

func (*Types_OneofStringVal) isTypes_OneofVal() {}

func (*Types_OneofInt64Val) isTypes_OneofVal() {}

func (*Types_OneofBoolVal) isTypes_OneofVal() {}

type OtherType1 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OtherStringVal *string                `protobuf:"bytes,1,req,name=other_string_val,json=otherStringVal" json:"other_string_val,omitempty"`
	OtherSecretVal *string                `protobuf:"bytes,2,req,name=other_secret_val,json=otherSecretVal" json:"other_secret_val,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OtherType1) Reset() {
	*x = OtherType1{}
	mi := &file_test_proto2types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherType1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherType1) ProtoMessage() {}

func (x *OtherType1) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto2types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherType1.ProtoReflect.Descriptor instead.
func (*OtherType1) Descriptor() ([]byte, []int) {
	return file_test_proto2types_types_proto_rawDescGZIP(), []int{1}
}

func (x *OtherType1) GetOtherStringVal() string {
	if x != nil && x.OtherStringVal != nil {
		return *x.OtherStringVal
	}
	return ""
}

func (x *OtherType1) GetOtherSecretVal() string {
	if x != nil && x.OtherSecretVal != nil {
		return *x.OtherSecretVal
	}
	return ""
}

type OtherType2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtherType2) Reset() {
	*x = OtherType2{}
	mi := &file_test_proto2types_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherType2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherType2) ProtoMessage() {}

func (x *OtherType2) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto2types_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherType2.ProtoReflect.Descriptor instead.
func (*OtherType2) Descriptor() ([]byte, []int) {
	return file_test_proto2types_types_proto_rawDescGZIP(), []int{2}
}

type OtherType3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *string                `protobuf:"bytes,1,req,name=val" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtherType3) Reset() {
	*x = OtherType3{}
	mi := &file_test_proto2types_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherType3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherType3) ProtoMessage() {}

func (x *OtherType3) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto2types_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherType3.ProtoReflect.Descriptor instead.
func (*OtherType3) Descriptor() ([]byte, []int) {
	return file_test_proto2types_types_proto_rawDescGZIP(), []int{3}
}

func (x *OtherType3) GetVal() string {
	if x != nil && x.Val != nil {
		return *x.Val
	}
	return ""
}

// Nested Types
// https://developers.google.com/protocol-buffers/docs/proto#nested
type Types_NestedType struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NestedStringVal *string                `protobuf:"bytes,1,req,name=nested_string_val,json=nestedStringVal" json:"nested_string_val,omitempty"`
	NestedSecretVal *string                `protobuf:"bytes,2,req,name=nested_secret_val,json=nestedSecretVal" json:"nested_secret_val,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Types_NestedType) Reset() {
	*x = Types_NestedType{}
	mi := &file_test_proto2types_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Types_NestedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Types_NestedType) ProtoMessage() {}

func (x *Types_NestedType) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto2types_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Types_NestedType.ProtoReflect.Descriptor instead.
func (*Types_NestedType) Descriptor() ([]byte, []int) {
	return file_test_proto2types_types_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Types_NestedType) GetNestedStringVal() string {
	if x != nil && x.NestedStringVal != nil {
		return *x.NestedStringVal
	}
	return ""
}

func (x *Types_NestedType) GetNestedSecretVal() string {
	if x != nil && x.NestedSecretVal != nil {
		return *x.NestedSecretVal
	}
	return ""
}

type OtherType2_NestedType struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NestedStringVal *string                `protobuf:"bytes,1,req,name=nested_string_val,json=nestedStringVal" json:"nested_string_val,omitempty"`
	NestedSecretVal *string                `protobuf:"bytes,2,req,name=nested_secret_val,json=nestedSecretVal" json:"nested_secret_val,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OtherType2_NestedType) Reset() {
	*x = OtherType2_NestedType{}
	mi := &file_test_proto2types_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherType2_NestedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherType2_NestedType) ProtoMessage() {}

func (x *OtherType2_NestedType) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto2types_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherType2_NestedType.ProtoReflect.Descriptor instead.
func (*OtherType2_NestedType) Descriptor() ([]byte, []int) {
	return file_test_proto2types_types_proto_rawDescGZIP(), []int{2, 0}
}

func (x *OtherType2_NestedType) GetNestedStringVal() string {
	if x != nil && x.NestedStringVal != nil {
		return *x.NestedStringVal
	}
	return ""
}

func (x *OtherType2_NestedType) GetNestedSecretVal() string {
	if x != nil && x.NestedSecretVal != nil {
		return *x.NestedSecretVal
	}
	return ""
}

var File_test_proto2types_types_proto protoreflect.FileDescriptor

const file_test_proto2types_types_proto_rawDesc = "" +
	"\n" +
	"\x1ctest/proto2types/types.proto\x12\vproto2types\x1a\x11marshal-zap.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa9\x12\n" +
	"\x05Types\x12#\n" +
	"\n" +
	"secret_val\x18\x01 \x02(\tB\x04\x88\xb5\x18\x01R\tsecretVal\x12$\n" +
	"\vsecret_val2\x18) \x02(\tB\x03\x80\x01\x01R\n" +
	"secretVal2\x12\x1d\n" +
	"\n" +
	"double_val\x18\x02 \x02(\x01R\tdoubleVal\x12\x1b\n" +
	"\tfloat_val\x18\x03 \x02(\x02R\bfloatVal\x12\x1b\n" +
	"\tint32_val\x18\x04 \x02(\x05R\bint32Val\x12\x1b\n" +
	"\tint64_val\x18\x05 \x02(\x03R\bint64Val\x12\x1d\n" +
	"\n" +
	"uint32_val\x18\x06 \x02(\rR\tuint32Val\x12\x1d\n" +
	"\n" +
	"uint64_val\x18\a \x02(\x04R\tuint64Val\x12\x1d\n" +
	"\n" +
	"sint32_val\x18\b \x02(\x11R\tsint32Val\x12\x1d\n" +
	"\n" +
	"sint64_val\x18\t \x02(\x12R\tsint64Val\x12\x1f\n" +
	"\vfixed32_val\x18\n" +
	" \x02(\aR\n" +
	"fixed32Val\x12\x1f\n" +
	"\vfixed64_val\x18\v \x02(\x06R\n" +
	"fixed64Val\x12!\n" +
	"\fsfixed32_val\x18\f \x02(\x0fR\vsfixed32Val\x12!\n" +
	"\fsfixed64_val\x18\r \x02(\x10R\vsfixed64Val\x12\x19\n" +
	"\bbool_val\x18\x0e \x02(\bR\aboolVal\x12\x1d\n" +
	"\n" +
	"string_val\x18\x0f \x02(\tR\tstringVal\x12\x1b\n" +
	"\tbytes_val\x18\x10 \x02(\fR\bbytesVal\x122\n" +
	"\benum_val\x18\x11 \x02(\x0e2\x17.proto2types.Types.EnumR\aenumVal\x12=\n" +
	"\x0eother_type_val\x18\x12 \x02(\v2\x17.proto2types.OtherType1R\fotherTypeVal\x12E\n" +
	"\x0fnested_type_val\x18\x13 \x02(\v2\x1d.proto2types.Types.NestedTypeR\rnestedTypeVal\x12^\n" +
	"\x1aother_type_nested_type_val\x18\x14 \x02(\v2\".proto2types.OtherType2.NestedTypeR\x16otherTypeNestedTypeVal\x12*\n" +
	"\x10oneof_string_val\x18\x15 \x01(\tH\x00R\x0eoneofStringVal\x12(\n" +
	"\x0foneof_int64_val\x18\x16 \x01(\x03H\x00R\roneofInt64Val\x12&\n" +
	"\x0eoneof_bool_val\x18\x17 \x01(\bH\x00R\foneofBoolVal\x12:\n" +
	"\bmap_val1\x18\x18 \x03(\v2\x1f.proto2types.Types.MapVal1EntryR\amapVal1\x12:\n" +
	"\bmap_val2\x18\x19 \x03(\v2\x1f.proto2types.Types.MapVal2EntryR\amapVal2\x12G\n" +
	"\rmap_empty_val\x18\x1a \x03(\v2#.proto2types.Types.MapEmptyValEntryR\vmapEmptyVal\x12#\n" +
	"\rrepeated_val1\x18\x1b \x03(\tR\frepeatedVal1\x12<\n" +
	"\rrepeated_val2\x18\x1c \x03(\x0e2\x17.proto2types.Types.EnumR\frepeatedVal2\x12<\n" +
	"\rrepeated_val3\x18\x1d \x03(\v2\x17.proto2types.OtherType1R\frepeatedVal3\x12,\n" +
	"\x12repeated_empty_val\x18\x1e \x03(\tR\x10repeatedEmptyVal\x126\n" +
	"\n" +
	"struct_val\x18\x1f \x02(\v2\x17.google.protobuf.StructR\tstructVal\x12\x17\n" +
	"\a_String\x18  \x02(\tR\x06String\x12!\n" +
	"\foptional_val\x18! \x01(\tR\voptionalVal\x127\n" +
	"\x18optional_not_present_val\x18\" \x01(\tR\x15optionalNotPresentVal\x12<\n" +
	"\roptional_enum\x18# \x01(\x0e2\x17.proto2types.Types.EnumR\foptionalEnum\x12R\n" +
	"\x19optional_not_present_enum\x18$ \x01(\x0e2\x17.proto2types.Types.EnumR\x16optionalNotPresentEnum\x12B\n" +
	"\x10optional_message\x18% \x01(\v2\x17.proto2types.OtherType3R\x0foptionalMessage\x12X\n" +
	"\x1coptional_not_present_message\x18& \x01(\v2\x17.proto2types.OtherType3R\x19optionalNotPresentMessage\x12@\n" +
	"\x0fpresent_message\x18' \x02(\v2\x17.proto2types.OtherType3R\x0epresentMessage\x12G\n" +
	"\x13not_present_message\x18( \x02(\v2\x17.proto2types.OtherType3R\x11notPresentMessage\x1aj\n" +
	"\n" +
	"NestedType\x12*\n" +
	"\x11nested_string_val\x18\x01 \x02(\tR\x0fnestedStringVal\x120\n" +
	"\x11nested_secret_val\x18\x02 \x02(\tB\x04\x88\xb5\x18\x01R\x0fnestedSecretVal\x1a:\n" +
	"\fMapVal1Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aS\n" +
	"\fMapVal2Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.proto2types.OtherType1R\x05value:\x028\x01\x1a>\n" +
	"\x10MapEmptyValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x04Enum\x12\n" +
	"\n" +
	"\x06ENUM_0\x10\x00\x12\n" +
	"\n" +
	"\x06ENUM_1\x10\x01\x12\n" +
	"\n" +
	"\x06ENUM_2\x10\x02B\v\n" +
	"\toneof_val\"f\n" +
	"\n" +
	"OtherType1\x12(\n" +
	"\x10other_string_val\x18\x01 \x02(\tR\x0eotherStringVal\x12.\n" +
	"\x10other_secret_val\x18\x02 \x02(\tB\x04\x88\xb5\x18\x01R\x0eotherSecretVal\"x\n" +
	"\n" +
	"OtherType2\x1aj\n" +
	"\n" +
	"NestedType\x12*\n" +
	"\x11nested_string_val\x18\x01 \x02(\tR\x0fnestedStringVal\x120\n" +
	"\x11nested_secret_val\x18\x02 \x02(\tB\x04\x88\xb5\x18\x01R\x0fnestedSecretVal\"\x1e\n" +
	"\n" +
	"OtherType3\x12\x10\n" +
	"\x03val\x18\x01 \x02(\tR\x03valBHZFgithub.com/kei2100/protoc-gen-marshal-zap/test/proto2types;proto2types"

var (
	file_test_proto2types_types_proto_rawDescOnce sync.Once
	file_test_proto2types_types_proto_rawDescData []byte
)

func file_test_proto2types_types_proto_rawDescGZIP() []byte {
	file_test_proto2types_types_proto_rawDescOnce.Do(func() {
		file_test_proto2types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto2types_types_proto_rawDesc), len(file_test_proto2types_types_proto_rawDesc)))
	})
	return file_test_proto2types_types_proto_rawDescData
}

var file_test_proto2types_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto2types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_test_proto2types_types_proto_goTypes = []any{
	(Types_Enum)(0),               // 0: proto2types.Types.Enum
	(*Types)(nil),                 // 1: proto2types.Types
	(*OtherType1)(nil),            // 2: proto2types.OtherType1
	(*OtherType2)(nil),            // 3: proto2types.OtherType2
	(*OtherType3)(nil),            // 4: proto2types.OtherType3
	(*Types_NestedType)(nil),      // 5: proto2types.Types.NestedType
	nil,                           // 6: proto2types.Types.MapVal1Entry
	nil,                           // 7: proto2types.Types.MapVal2Entry
	nil,                           // 8: proto2types.Types.MapEmptyValEntry
	(*OtherType2_NestedType)(nil), // 9: proto2types.OtherType2.NestedType
	(*structpb.Struct)(nil),       // 10: google.protobuf.Struct
}
var file_test_proto2types_types_proto_depIdxs = []int32{
	0,  // 0: proto2types.Types.enum_val:type_name -> proto2types.Types.Enum
	2,  // 1: proto2types.Types.other_type_val:type_name -> proto2types.OtherType1
	5,  // 2: proto2types.Types.nested_type_val:type_name -> proto2types.Types.NestedType
	9,  // 3: proto2types.Types.other_type_nested_type_val:type_name -> proto2types.OtherType2.NestedType
	6,  // 4: proto2types.Types.map_val1:type_name -> proto2types.Types.MapVal1Entry
	7,  // 5: proto2types.Types.map_val2:type_name -> proto2types.Types.MapVal2Entry
	8,  // 6: proto2types.Types.map_empty_val:type_name -> proto2types.Types.MapEmptyValEntry
	0,  // 7: proto2types.Types.repeated_val2:type_name -> proto2types.Types.Enum
	2,  // 8: proto2types.Types.repeated_val3:type_name -> proto2types.OtherType1
	10, // 9: proto2types.Types.struct_val:type_name -> google.protobuf.Struct
	0,  // 10: proto2types.Types.optional_enum:type_name -> proto2types.Types.Enum
	0,  // 11: proto2types.Types.optional_not_present_enum:type_name -> proto2types.Types.Enum
	4,  // 12: proto2types.Types.optional_message:type_name -> proto2types.OtherType3
	4,  // 13: proto2types.Types.optional_not_present_message:type_name -> proto2types.OtherType3
	4,  // 14: proto2types.Types.present_message:type_name -> proto2types.OtherType3
	4,  // 15: proto2types.Types.not_present_message:type_name -> proto2types.OtherType3
	2,  // 16: proto2types.Types.MapVal2Entry.value:type_name -> proto2types.OtherType1
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_test_proto2types_types_proto_init() }
func file_test_proto2types_types_proto_init() {
	if File_test_proto2types_types_proto != nil {
		return
	}
	file_test_proto2types_types_proto_msgTypes[0].OneofWrappers = []any{
		(*Types_OneofStringVal)(nil),
		(*Types_OneofInt64Val)(nil),
		(*Types_OneofBoolVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto2types_types_proto_rawDesc), len(file_test_proto2types_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto2types_types_proto_goTypes,
		DependencyIndexes: file_test_proto2types_types_proto_depIdxs,
		EnumInfos:         file_test_proto2types_types_proto_enumTypes,
		MessageInfos:      file_test_proto2types_types_proto_msgTypes,
	}.Build()
	File_test_proto2types_types_proto = out.File
	file_test_proto2types_types_proto_goTypes = nil
	file_test_proto2types_types_proto_depIdxs = nil
}
