// Code generated by protoc-gen-marshal-zap. DO NOT EDIT.
//
// source: test/proto2types/types.proto

package proto2types

import (
	fmt "fmt"
	zapcore "go.uber.org/zap/zapcore"
)

func (x *Types) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if x == nil {
		return nil
	}

	enc.AddString("secret_val", "[MASKED]")

	enc.AddString("secret_val2", "[MASKED]")

	if x.DoubleVal != nil {
		enc.AddFloat64("double_val", x.GetDoubleVal())
	}

	if x.FloatVal != nil {
		enc.AddFloat32("float_val", x.GetFloatVal())
	}

	if x.Int32Val != nil {
		enc.AddInt32("int32_val", x.GetInt32Val())
	}

	if x.Int64Val != nil {
		enc.AddInt64("int64_val", x.GetInt64Val())
	}

	if x.Uint32Val != nil {
		enc.AddUint32("uint32_val", x.GetUint32Val())
	}

	if x.Uint64Val != nil {
		enc.AddUint64("uint64_val", x.GetUint64Val())
	}

	if x.Sint32Val != nil {
		enc.AddInt32("sint32_val", x.GetSint32Val())
	}

	if x.Sint64Val != nil {
		enc.AddInt64("sint64_val", x.GetSint64Val())
	}

	if x.Fixed32Val != nil {
		enc.AddUint32("fixed32_val", x.GetFixed32Val())
	}

	if x.Fixed64Val != nil {
		enc.AddUint64("fixed64_val", x.GetFixed64Val())
	}

	if x.Sfixed32Val != nil {
		enc.AddInt32("sfixed32_val", x.GetSfixed32Val())
	}

	if x.Sfixed64Val != nil {
		enc.AddInt64("sfixed64_val", x.GetSfixed64Val())
	}

	if x.BoolVal != nil {
		enc.AddBool("bool_val", x.GetBoolVal())
	}

	if x.StringVal != nil {
		enc.AddString("string_val", x.GetStringVal())
	}

	if x.BytesVal != nil {
		enc.AddBinary("bytes_val", x.GetBytesVal())
	}

	if x.EnumVal != nil {
		enc.AddString("enum_val", x.GetEnumVal().String())
	}

	if x.OtherTypeVal != nil {
		if obj, ok := interface{}(x.GetOtherTypeVal()).(zapcore.ObjectMarshaler); ok {
			enc.AddObject("other_type_val", obj)
		} else {
			enc.AddReflected("other_type_val", x.GetOtherTypeVal())
		}
	}

	if x.NestedTypeVal != nil {
		if obj, ok := interface{}(x.GetNestedTypeVal()).(zapcore.ObjectMarshaler); ok {
			enc.AddObject("nested_type_val", obj)
		} else {
			enc.AddReflected("nested_type_val", x.GetNestedTypeVal())
		}
	}

	if x.OtherTypeNestedTypeVal != nil {
		if obj, ok := interface{}(x.GetOtherTypeNestedTypeVal()).(zapcore.ObjectMarshaler); ok {
			enc.AddObject("other_type_nested_type_val", obj)
		} else {
			enc.AddReflected("other_type_nested_type_val", x.GetOtherTypeNestedTypeVal())
		}
	}

	if _, ok := x.GetOneofVal().(*Types_OneofStringVal); ok {
		enc.AddString("oneof_string_val", x.GetOneofStringVal())
	}

	if _, ok := x.GetOneofVal().(*Types_OneofInt64Val); ok {
		enc.AddInt64("oneof_int64_val", x.GetOneofInt64Val())
	}

	if _, ok := x.GetOneofVal().(*Types_OneofBoolVal); ok {
		enc.AddBool("oneof_bool_val", x.GetOneofBoolVal())
	}

	enc.AddObject("map_val1", zapcore.ObjectMarshalerFunc(func(enc zapcore.ObjectEncoder) error {
		for k, v := range x.MapVal1 {
			enc.AddString(fmt.Sprintf("%v", k), v)
		}
		return nil
	}))

	enc.AddObject("map_val2", zapcore.ObjectMarshalerFunc(func(enc zapcore.ObjectEncoder) error {
		for k, v := range x.MapVal2 {
			if obj, ok := interface{}(v).(zapcore.ObjectMarshaler); ok {
				enc.AddObject(fmt.Sprintf("%v", k), obj)
			} else {
				enc.AddReflected(fmt.Sprintf("%v", k), v)
			}
		}
		return nil
	}))

	enc.AddObject("map_empty_val", zapcore.ObjectMarshalerFunc(func(enc zapcore.ObjectEncoder) error {
		for k, v := range x.MapEmptyVal {
			enc.AddString(fmt.Sprintf("%v", k), v)
		}
		return nil
	}))

	repeated_val1ArrMarshaller := func(enc zapcore.ArrayEncoder) error {
		for _, v := range x.RepeatedVal1 {
			enc.AppendString(v)
		}
		return nil
	}
	enc.AddArray("repeated_val1", zapcore.ArrayMarshalerFunc(repeated_val1ArrMarshaller))

	repeated_val2ArrMarshaller := func(enc zapcore.ArrayEncoder) error {
		for _, v := range x.RepeatedVal2 {
			enc.AppendString(v.String())
		}
		return nil
	}
	enc.AddArray("repeated_val2", zapcore.ArrayMarshalerFunc(repeated_val2ArrMarshaller))

	repeated_val3ArrMarshaller := func(enc zapcore.ArrayEncoder) error {
		for _, v := range x.RepeatedVal3 {
			if obj, ok := interface{}(v).(zapcore.ObjectMarshaler); ok {
				enc.AppendObject(obj)
			} else {
				enc.AppendReflected(v)
			}
		}
		return nil
	}
	enc.AddArray("repeated_val3", zapcore.ArrayMarshalerFunc(repeated_val3ArrMarshaller))

	repeated_empty_valArrMarshaller := func(enc zapcore.ArrayEncoder) error {
		for _, v := range x.RepeatedEmptyVal {
			enc.AppendString(v)
		}
		return nil
	}
	enc.AddArray("repeated_empty_val", zapcore.ArrayMarshalerFunc(repeated_empty_valArrMarshaller))

	if x.StructVal != nil {
		if obj, ok := interface{}(x.GetStructVal()).(zapcore.ObjectMarshaler); ok {
			enc.AddObject("struct_val", obj)
		} else {
			enc.AddReflected("struct_val", x.GetStructVal())
		}
	}

	if x.XString != nil {
		enc.AddString("_String", x.GetXString())
	}

	if x.OptionalVal != nil {
		enc.AddString("optional_val", x.GetOptionalVal())
	}

	if x.OptionalNotPresentVal != nil {
		enc.AddString("optional_not_present_val", x.GetOptionalNotPresentVal())
	}

	if x.OptionalEnum != nil {
		enc.AddString("optional_enum", x.GetOptionalEnum().String())
	}

	if x.OptionalNotPresentEnum != nil {
		enc.AddString("optional_not_present_enum", x.GetOptionalNotPresentEnum().String())
	}

	if x.OptionalMessage != nil {
		if obj, ok := interface{}(x.GetOptionalMessage()).(zapcore.ObjectMarshaler); ok {
			enc.AddObject("optional_message", obj)
		} else {
			enc.AddReflected("optional_message", x.GetOptionalMessage())
		}
	}

	if x.OptionalNotPresentMessage != nil {
		if obj, ok := interface{}(x.GetOptionalNotPresentMessage()).(zapcore.ObjectMarshaler); ok {
			enc.AddObject("optional_not_present_message", obj)
		} else {
			enc.AddReflected("optional_not_present_message", x.GetOptionalNotPresentMessage())
		}
	}

	if x.PresentMessage != nil {
		if obj, ok := interface{}(x.GetPresentMessage()).(zapcore.ObjectMarshaler); ok {
			enc.AddObject("present_message", obj)
		} else {
			enc.AddReflected("present_message", x.GetPresentMessage())
		}
	}

	if x.NotPresentMessage != nil {
		if obj, ok := interface{}(x.GetNotPresentMessage()).(zapcore.ObjectMarshaler); ok {
			enc.AddObject("not_present_message", obj)
		} else {
			enc.AddReflected("not_present_message", x.GetNotPresentMessage())
		}
	}

	return nil
}

func (x *Types_NestedType) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if x == nil {
		return nil
	}

	if x.NestedStringVal != nil {
		enc.AddString("nested_string_val", x.GetNestedStringVal())
	}

	enc.AddString("nested_secret_val", "[MASKED]")

	return nil
}

func (x *OtherType1) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if x == nil {
		return nil
	}

	if x.OtherStringVal != nil {
		enc.AddString("other_string_val", x.GetOtherStringVal())
	}

	enc.AddString("other_secret_val", "[MASKED]")

	return nil
}

func (x *OtherType2) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if x == nil {
		return nil
	}

	return nil
}

func (x *OtherType2_NestedType) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if x == nil {
		return nil
	}

	if x.NestedStringVal != nil {
		enc.AddString("nested_string_val", x.GetNestedStringVal())
	}

	enc.AddString("nested_secret_val", "[MASKED]")

	return nil
}

func (x *OtherType3) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if x == nil {
		return nil
	}

	if x.Val != nil {
		enc.AddString("val", x.GetVal())
	}

	return nil
}
