// Code generated by protoc-gen-marshal-zap. DO NOT EDIT.
// source: github.com/kei2100/protoc-gen-marshal-zap/test/types/types.pb.go

package types

import (
	"go.uber.org/zap/zapcore"
	"strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = zapcore.NewNopCore
var _ = strconv.FormatInt

func (m *Types) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if m == nil {
		return nil
	}

	enc.AddString("secret1", "[MASKED]")

	enc.AddFloat64("double1", m.Double1)

	return nil
}
