// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: test/types/types.proto

package types

import (
	_ "github.com/kei2100/protoc-gen-marshal-zap"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumerations
// https://developers.google.com/protocol-buffers/docs/proto#enum
type Types_Enum int32

const (
	Types_ENUM_0 Types_Enum = 0
	Types_ENUM_1 Types_Enum = 1
	Types_ENUM_2 Types_Enum = 2
)

// Enum value maps for Types_Enum.
var (
	Types_Enum_name = map[int32]string{
		0: "ENUM_0",
		1: "ENUM_1",
		2: "ENUM_2",
	}
	Types_Enum_value = map[string]int32{
		"ENUM_0": 0,
		"ENUM_1": 1,
		"ENUM_2": 2,
	}
)

func (x Types_Enum) Enum() *Types_Enum {
	p := new(Types_Enum)
	*p = x
	return p
}

func (x Types_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Types_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_test_types_types_proto_enumTypes[0].Descriptor()
}

func (Types_Enum) Type() protoreflect.EnumType {
	return &file_test_types_types_proto_enumTypes[0]
}

func (x Types_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Types_Enum.Descriptor instead.
func (Types_Enum) EnumDescriptor() ([]byte, []int) {
	return file_test_types_types_proto_rawDescGZIP(), []int{0, 0}
}

type Types struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SecretVal  string                 `protobuf:"bytes,1,opt,name=secret_val,json=secretVal,proto3" json:"secret_val,omitempty"`
	SecretVal2 string                 `protobuf:"bytes,41,opt,name=secret_val2,json=secretVal2,proto3" json:"secret_val2,omitempty"`
	// Scalar Value Types
	// https://developers.google.com/protocol-buffers/docs/proto#scalar
	DoubleVal   float64    `protobuf:"fixed64,2,opt,name=double_val,json=doubleVal,proto3" json:"double_val,omitempty"`
	FloatVal    float32    `protobuf:"fixed32,3,opt,name=float_val,json=floatVal,proto3" json:"float_val,omitempty"`
	Int32Val    int32      `protobuf:"varint,4,opt,name=int32_val,json=int32Val,proto3" json:"int32_val,omitempty"`
	Int64Val    int64      `protobuf:"varint,5,opt,name=int64_val,json=int64Val,proto3" json:"int64_val,omitempty"`
	Uint32Val   uint32     `protobuf:"varint,6,opt,name=uint32_val,json=uint32Val,proto3" json:"uint32_val,omitempty"`
	Uint64Val   uint64     `protobuf:"varint,7,opt,name=uint64_val,json=uint64Val,proto3" json:"uint64_val,omitempty"`
	Sint32Val   int32      `protobuf:"zigzag32,8,opt,name=sint32_val,json=sint32Val,proto3" json:"sint32_val,omitempty"`
	Sint64Val   int64      `protobuf:"zigzag64,9,opt,name=sint64_val,json=sint64Val,proto3" json:"sint64_val,omitempty"`
	Fixed32Val  uint32     `protobuf:"fixed32,10,opt,name=fixed32_val,json=fixed32Val,proto3" json:"fixed32_val,omitempty"`
	Fixed64Val  uint64     `protobuf:"fixed64,11,opt,name=fixed64_val,json=fixed64Val,proto3" json:"fixed64_val,omitempty"`
	Sfixed32Val int32      `protobuf:"fixed32,12,opt,name=sfixed32_val,json=sfixed32Val,proto3" json:"sfixed32_val,omitempty"`
	Sfixed64Val int64      `protobuf:"fixed64,13,opt,name=sfixed64_val,json=sfixed64Val,proto3" json:"sfixed64_val,omitempty"`
	BoolVal     bool       `protobuf:"varint,14,opt,name=bool_val,json=boolVal,proto3" json:"bool_val,omitempty"`
	StringVal   string     `protobuf:"bytes,15,opt,name=string_val,json=stringVal,proto3" json:"string_val,omitempty"`
	BytesVal    []byte     `protobuf:"bytes,16,opt,name=bytes_val,json=bytesVal,proto3" json:"bytes_val,omitempty"`
	EnumVal     Types_Enum `protobuf:"varint,17,opt,name=enum_val,json=enumVal,proto3,enum=types.Types_Enum" json:"enum_val,omitempty"`
	// Other Message Types
	// https://developers.google.com/protocol-buffers/docs/proto#other
	OtherTypeVal           *OtherType1            `protobuf:"bytes,18,opt,name=other_type_val,json=otherTypeVal,proto3" json:"other_type_val,omitempty"`
	NestedTypeVal          *Types_NestedType      `protobuf:"bytes,19,opt,name=nested_type_val,json=nestedTypeVal,proto3" json:"nested_type_val,omitempty"`
	OtherTypeNestedTypeVal *OtherType2_NestedType `protobuf:"bytes,20,opt,name=other_type_nested_type_val,json=otherTypeNestedTypeVal,proto3" json:"other_type_nested_type_val,omitempty"`
	// Oneof
	// https://developers.google.com/protocol-buffers/docs/proto#oneof
	//
	// Types that are valid to be assigned to OneofVal:
	//
	//	*Types_OneofStringVal
	//	*Types_OneofInt64Val
	//	*Types_OneofBoolVal
	OneofVal isTypes_OneofVal `protobuf_oneof:"oneof_val"`
	// Maps
	// https://developers.google.com/protocol-buffers/docs/proto#updating
	MapVal1     map[string]string      `protobuf:"bytes,24,rep,name=map_val1,json=mapVal1,proto3" json:"map_val1,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapVal2     map[string]*OtherType1 `protobuf:"bytes,25,rep,name=map_val2,json=mapVal2,proto3" json:"map_val2,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapEmptyVal map[string]string      `protobuf:"bytes,26,rep,name=map_empty_val,json=mapEmptyVal,proto3" json:"map_empty_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Repeated
	// * Repeated Scalar Values
	// * Repeated Enumerations
	// * Repeated MessageTypes
	// * (Repeated Maps -> NOT supported)
	// * (Repeated Repeated -> NOT supported)
	RepeatedVal1     []string      `protobuf:"bytes,27,rep,name=repeated_val1,json=repeatedVal1,proto3" json:"repeated_val1,omitempty"`
	RepeatedVal2     []Types_Enum  `protobuf:"varint,28,rep,packed,name=repeated_val2,json=repeatedVal2,proto3,enum=types.Types_Enum" json:"repeated_val2,omitempty"`
	RepeatedVal3     []*OtherType1 `protobuf:"bytes,29,rep,name=repeated_val3,json=repeatedVal3,proto3" json:"repeated_val3,omitempty"`
	RepeatedEmptyVal []string      `protobuf:"bytes,30,rep,name=repeated_empty_val,json=repeatedEmptyVal,proto3" json:"repeated_empty_val,omitempty"`
	// Well-Known Types are covered by the WellKnownTypes message below.
	// Struct is kept here to verify the generic message fallback.
	StructVal *structpb.Struct `protobuf:"bytes,31,opt,name=struct_val,json=structVal,proto3" json:"struct_val,omitempty"`
	// Camelcasing
	XString string `protobuf:"bytes,32,opt,name=_String,json=String,proto3" json:"_String,omitempty"`
	// Handle Explicit Presence
	// https://protobuf.dev/programming-guides/field_presence/#presence-in-proto3-apis
	OptionalVal               *string     `protobuf:"bytes,33,opt,name=optional_val,json=optionalVal,proto3,oneof" json:"optional_val,omitempty"`
	OptionalNotPresentVal     *string     `protobuf:"bytes,34,opt,name=optional_not_present_val,json=optionalNotPresentVal,proto3,oneof" json:"optional_not_present_val,omitempty"`
	OptionalEnum              *Types_Enum `protobuf:"varint,35,opt,name=optional_enum,json=optionalEnum,proto3,enum=types.Types_Enum,oneof" json:"optional_enum,omitempty"`
	OptionalNotPresentEnum    *Types_Enum `protobuf:"varint,36,opt,name=optional_not_present_enum,json=optionalNotPresentEnum,proto3,enum=types.Types_Enum,oneof" json:"optional_not_present_enum,omitempty"`
	OptionalMessage           *OtherType3 `protobuf:"bytes,37,opt,name=optional_message,json=optionalMessage,proto3,oneof" json:"optional_message,omitempty"`
	OptionalNotPresentMessage *OtherType3 `protobuf:"bytes,38,opt,name=optional_not_present_message,json=optionalNotPresentMessage,proto3,oneof" json:"optional_not_present_message,omitempty"`
	PresentMessage            *OtherType3 `protobuf:"bytes,39,opt,name=present_message,json=presentMessage,proto3" json:"present_message,omitempty"`
	NotPresentMessage         *OtherType3 `protobuf:"bytes,40,opt,name=not_present_message,json=notPresentMessage,proto3" json:"not_present_message,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Types) Reset() {
	*x = Types{}
	mi := &file_test_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Types) ProtoMessage() {}

func (x *Types) ProtoReflect() protoreflect.Message {
	mi := &file_test_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Types.ProtoReflect.Descriptor instead.
func (*Types) Descriptor() ([]byte, []int) {
	return file_test_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *Types) GetSecretVal() string {
	if x != nil {
		return x.SecretVal
	}
	return ""
}

func (x *Types) GetSecretVal2() string {
	if x != nil {
		return x.SecretVal2
	}
	return ""
}

func (x *Types) GetDoubleVal() float64 {
	if x != nil {
		return x.DoubleVal
	}
	return 0
}

func (x *Types) GetFloatVal() float32 {
	if x != nil {
		return x.FloatVal
	}
	return 0
}

func (x *Types) GetInt32Val() int32 {
	if x != nil {
		return x.Int32Val
	}
	return 0
}

func (x *Types) GetInt64Val() int64 {
	if x != nil {
		return x.Int64Val
	}
	return 0
}

func (x *Types) GetUint32Val() uint32 {
	if x != nil {
		return x.Uint32Val
	}
	return 0
}

func (x *Types) GetUint64Val() uint64 {
	if x != nil {
		return x.Uint64Val
	}
	return 0
}

func (x *Types) GetSint32Val() int32 {
	if x != nil {
		return x.Sint32Val
	}
	return 0
}

func (x *Types) GetSint64Val() int64 {
	if x != nil {
		return x.Sint64Val
	}
	return 0
}

func (x *Types) GetFixed32Val() uint32 {
	if x != nil {
		return x.Fixed32Val
	}
	return 0
}

func (x *Types) GetFixed64Val() uint64 {
	if x != nil {
		return x.Fixed64Val
	}
	return 0
}

func (x *Types) GetSfixed32Val() int32 {
	if x != nil {
		return x.Sfixed32Val
	}
	return 0
}

func (x *Types) GetSfixed64Val() int64 {
	if x != nil {
		return x.Sfixed64Val
	}
	return 0
}

func (x *Types) GetBoolVal() bool {
	if x != nil {
		return x.BoolVal
	}
	return false
}

func (x *Types) GetStringVal() string {
	if x != nil {
		return x.StringVal
	}
	return ""
}

func (x *Types) GetBytesVal() []byte {
	if x != nil {
		return x.BytesVal
	}
	return nil
}

func (x *Types) GetEnumVal() Types_Enum {
	if x != nil {
		return x.EnumVal
	}
	return Types_ENUM_0
}

func (x *Types) GetOtherTypeVal() *OtherType1 {
	if x != nil {
		return x.OtherTypeVal
	}
	return nil
}

func (x *Types) GetNestedTypeVal() *Types_NestedType {
	if x != nil {
		return x.NestedTypeVal
	}
	return nil
}

func (x *Types) GetOtherTypeNestedTypeVal() *OtherType2_NestedType {
	if x != nil {
		return x.OtherTypeNestedTypeVal
	}
	return nil
}

func (x *Types) GetOneofVal() isTypes_OneofVal {
	if x != nil {
		return x.OneofVal
	}
	return nil
}

func (x *Types) GetOneofStringVal() string {
	if x != nil {
		if x, ok := x.OneofVal.(*Types_OneofStringVal); ok {
			return x.OneofStringVal
		}
	}
	return ""
}

func (x *Types) GetOneofInt64Val() int64 {
	if x != nil {
		if x, ok := x.OneofVal.(*Types_OneofInt64Val); ok {
			return x.OneofInt64Val
		}
	}
	return 0
}

func (x *Types) GetOneofBoolVal() bool {
	if x != nil {
		if x, ok := x.OneofVal.(*Types_OneofBoolVal); ok {
			return x.OneofBoolVal
		}
	}
	return false
}

func (x *Types) GetMapVal1() map[string]string {
	if x != nil {
		return x.MapVal1
	}
	return nil
}

func (x *Types) GetMapVal2() map[string]*OtherType1 {
	if x != nil {
		return x.MapVal2
	}
	return nil
}

func (x *Types) GetMapEmptyVal() map[string]string {
	if x != nil {
		return x.MapEmptyVal
	}
	return nil
}

func (x *Types) GetRepeatedVal1() []string {
	if x != nil {
		return x.RepeatedVal1
	}
	return nil
}

func (x *Types) GetRepeatedVal2() []Types_Enum {
	if x != nil {
		return x.RepeatedVal2
	}
	return nil
}

func (x *Types) GetRepeatedVal3() []*OtherType1 {
	if x != nil {
		return x.RepeatedVal3
	}
	return nil
}

func (x *Types) GetRepeatedEmptyVal() []string {
	if x != nil {
		return x.RepeatedEmptyVal
	}
	return nil
}

func (x *Types) GetStructVal() *structpb.Struct {
	if x != nil {
		return x.StructVal
	}
	return nil
}

func (x *Types) GetXString() string {
	if x != nil {
		return x.XString
	}
	return ""
}

func (x *Types) GetOptionalVal() string {
	if x != nil && x.OptionalVal != nil {
		return *x.OptionalVal
	}
	return ""
}

func (x *Types) GetOptionalNotPresentVal() string {
	if x != nil && x.OptionalNotPresentVal != nil {
		return *x.OptionalNotPresentVal
	}
	return ""
}

func (x *Types) GetOptionalEnum() Types_Enum {
	if x != nil && x.OptionalEnum != nil {
		return *x.OptionalEnum
	}
	return Types_ENUM_0
}

func (x *Types) GetOptionalNotPresentEnum() Types_Enum {
	if x != nil && x.OptionalNotPresentEnum != nil {
		return *x.OptionalNotPresentEnum
	}
	return Types_ENUM_0
}

func (x *Types) GetOptionalMessage() *OtherType3 {
	if x != nil {
		return x.OptionalMessage
	}
	return nil
}

func (x *Types) GetOptionalNotPresentMessage() *OtherType3 {
	if x != nil {
		return x.OptionalNotPresentMessage
	}
	return nil
}

func (x *Types) GetPresentMessage() *OtherType3 {
	if x != nil {
		return x.PresentMessage
	}
	return nil
}

func (x *Types) GetNotPresentMessage() *OtherType3 {
	if x != nil {
		return x.NotPresentMessage
	}
	return nil
}

type isTypes_OneofVal interface {
	isTypes_OneofVal()
}

type Types_OneofStringVal struct {
	OneofStringVal string `protobuf:"bytes,21,opt,name=oneof_string_val,json=oneofStringVal,proto3,oneof"`
}

type Types_OneofInt64Val struct {
	OneofInt64Val int64 `protobuf:"varint,22,opt,name=oneof_int64_val,json=oneofInt64Val,proto3,oneof"`
}

type Types_OneofBoolVal struct {
	OneofBoolVal bool `protobuf:"varint,23,opt,name=oneof_bool_val,json=oneofBoolVal,proto3,oneof"`
}

func (*Types_OneofStringVal) isTypes_OneofVal() {}

func (*Types_OneofInt64Val) isTypes_OneofVal() {}

func (*Types_OneofBoolVal) isTypes_OneofVal() {}

type OtherType1 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OtherStringVal string                 `protobuf:"bytes,1,opt,name=other_string_val,json=otherStringVal,proto3" json:"other_string_val,omitempty"`
	OtherSecretVal string                 `protobuf:"bytes,2,opt,name=other_secret_val,json=otherSecretVal,proto3" json:"other_secret_val,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OtherType1) Reset() {
	*x = OtherType1{}
	mi := &file_test_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherType1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherType1) ProtoMessage() {}

func (x *OtherType1) ProtoReflect() protoreflect.Message {
	mi := &file_test_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherType1.ProtoReflect.Descriptor instead.
func (*OtherType1) Descriptor() ([]byte, []int) {
	return file_test_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *OtherType1) GetOtherStringVal() string {
	if x != nil {
		return x.OtherStringVal
	}
	return ""
}

func (x *OtherType1) GetOtherSecretVal() string {
	if x != nil {
		return x.OtherSecretVal
	}
	return ""
}

type OtherType2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtherType2) Reset() {
	*x = OtherType2{}
	mi := &file_test_types_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherType2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherType2) ProtoMessage() {}

func (x *OtherType2) ProtoReflect() protoreflect.Message {
	mi := &file_test_types_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherType2.ProtoReflect.Descriptor instead.
func (*OtherType2) Descriptor() ([]byte, []int) {
	return file_test_types_types_proto_rawDescGZIP(), []int{2}
}

type OtherType3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtherType3) Reset() {
	*x = OtherType3{}
	mi := &file_test_types_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherType3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherType3) ProtoMessage() {}

func (x *OtherType3) ProtoReflect() protoreflect.Message {
	mi := &file_test_types_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherType3.ProtoReflect.Descriptor instead.
func (*OtherType3) Descriptor() ([]byte, []int) {
	return file_test_types_types_proto_rawDescGZIP(), []int{3}
}

func (x *OtherType3) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

// Well-Known Types
// https://protobuf.dev/reference/protobuf/google.protobuf/
type WellKnownTypes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Singular
	TimestampVal   *timestamppb.Timestamp  `protobuf:"bytes,1,opt,name=timestamp_val,json=timestampVal,proto3" json:"timestamp_val,omitempty"`
	DurationVal    *durationpb.Duration    `protobuf:"bytes,2,opt,name=duration_val,json=durationVal,proto3" json:"duration_val,omitempty"`
	BoolValueVal   *wrapperspb.BoolValue   `protobuf:"bytes,3,opt,name=bool_value_val,json=boolValueVal,proto3" json:"bool_value_val,omitempty"`
	StringValueVal *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=string_value_val,json=stringValueVal,proto3" json:"string_value_val,omitempty"`
	BytesValueVal  *wrapperspb.BytesValue  `protobuf:"bytes,5,opt,name=bytes_value_val,json=bytesValueVal,proto3" json:"bytes_value_val,omitempty"`
	Int32ValueVal  *wrapperspb.Int32Value  `protobuf:"bytes,6,opt,name=int32_value_val,json=int32ValueVal,proto3" json:"int32_value_val,omitempty"`
	Int64ValueVal  *wrapperspb.Int64Value  `protobuf:"bytes,7,opt,name=int64_value_val,json=int64ValueVal,proto3" json:"int64_value_val,omitempty"`
	Uint32ValueVal *wrapperspb.UInt32Value `protobuf:"bytes,8,opt,name=uint32_value_val,json=uint32ValueVal,proto3" json:"uint32_value_val,omitempty"`
	Uint64ValueVal *wrapperspb.UInt64Value `protobuf:"bytes,9,opt,name=uint64_value_val,json=uint64ValueVal,proto3" json:"uint64_value_val,omitempty"`
	FloatValueVal  *wrapperspb.FloatValue  `protobuf:"bytes,10,opt,name=float_value_val,json=floatValueVal,proto3" json:"float_value_val,omitempty"`
	DoubleValueVal *wrapperspb.DoubleValue `protobuf:"bytes,11,opt,name=double_value_val,json=doubleValueVal,proto3" json:"double_value_val,omitempty"`
	FieldMaskVal   *fieldmaskpb.FieldMask  `protobuf:"bytes,12,opt,name=field_mask_val,json=fieldMaskVal,proto3" json:"field_mask_val,omitempty"`
	EmptyVal       *emptypb.Empty          `protobuf:"bytes,13,opt,name=empty_val,json=emptyVal,proto3" json:"empty_val,omitempty"`
	// Not specially handled (generic message fallback)
	AnyVal       *anypb.Any          `protobuf:"bytes,14,opt,name=any_val,json=anyVal,proto3" json:"any_val,omitempty"`
	StructVal    *structpb.Struct    `protobuf:"bytes,15,opt,name=struct_val,json=structVal,proto3" json:"struct_val,omitempty"`
	ValueVal     *structpb.Value     `protobuf:"bytes,16,opt,name=value_val,json=valueVal,proto3" json:"value_val,omitempty"`
	ListValueVal *structpb.ListValue `protobuf:"bytes,17,opt,name=list_value_val,json=listValueVal,proto3" json:"list_value_val,omitempty"`
	// Not present
	NotPresentTimestampVal   *timestamppb.Timestamp  `protobuf:"bytes,18,opt,name=not_present_timestamp_val,json=notPresentTimestampVal,proto3" json:"not_present_timestamp_val,omitempty"`
	NotPresentStringValueVal *wrapperspb.StringValue `protobuf:"bytes,19,opt,name=not_present_string_value_val,json=notPresentStringValueVal,proto3" json:"not_present_string_value_val,omitempty"`
	NotPresentEmptyVal       *emptypb.Empty          `protobuf:"bytes,20,opt,name=not_present_empty_val,json=notPresentEmptyVal,proto3" json:"not_present_empty_val,omitempty"`
	// Masked
	MaskedTimestampVal *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=masked_timestamp_val,json=maskedTimestampVal,proto3" json:"masked_timestamp_val,omitempty"`
	// Repeated
	RepeatedTimestampVal   []*timestamppb.Timestamp  `protobuf:"bytes,31,rep,name=repeated_timestamp_val,json=repeatedTimestampVal,proto3" json:"repeated_timestamp_val,omitempty"`
	RepeatedDurationVal    []*durationpb.Duration    `protobuf:"bytes,32,rep,name=repeated_duration_val,json=repeatedDurationVal,proto3" json:"repeated_duration_val,omitempty"`
	RepeatedBoolValueVal   []*wrapperspb.BoolValue   `protobuf:"bytes,33,rep,name=repeated_bool_value_val,json=repeatedBoolValueVal,proto3" json:"repeated_bool_value_val,omitempty"`
	RepeatedStringValueVal []*wrapperspb.StringValue `protobuf:"bytes,34,rep,name=repeated_string_value_val,json=repeatedStringValueVal,proto3" json:"repeated_string_value_val,omitempty"`
	RepeatedBytesValueVal  []*wrapperspb.BytesValue  `protobuf:"bytes,35,rep,name=repeated_bytes_value_val,json=repeatedBytesValueVal,proto3" json:"repeated_bytes_value_val,omitempty"`
	RepeatedInt32ValueVal  []*wrapperspb.Int32Value  `protobuf:"bytes,36,rep,name=repeated_int32_value_val,json=repeatedInt32ValueVal,proto3" json:"repeated_int32_value_val,omitempty"`
	RepeatedInt64ValueVal  []*wrapperspb.Int64Value  `protobuf:"bytes,37,rep,name=repeated_int64_value_val,json=repeatedInt64ValueVal,proto3" json:"repeated_int64_value_val,omitempty"`
	RepeatedUint32ValueVal []*wrapperspb.UInt32Value `protobuf:"bytes,38,rep,name=repeated_uint32_value_val,json=repeatedUint32ValueVal,proto3" json:"repeated_uint32_value_val,omitempty"`
	RepeatedUint64ValueVal []*wrapperspb.UInt64Value `protobuf:"bytes,39,rep,name=repeated_uint64_value_val,json=repeatedUint64ValueVal,proto3" json:"repeated_uint64_value_val,omitempty"`
	RepeatedFloatValueVal  []*wrapperspb.FloatValue  `protobuf:"bytes,40,rep,name=repeated_float_value_val,json=repeatedFloatValueVal,proto3" json:"repeated_float_value_val,omitempty"`
	RepeatedDoubleValueVal []*wrapperspb.DoubleValue `protobuf:"bytes,41,rep,name=repeated_double_value_val,json=repeatedDoubleValueVal,proto3" json:"repeated_double_value_val,omitempty"`
	RepeatedFieldMaskVal   []*fieldmaskpb.FieldMask  `protobuf:"bytes,42,rep,name=repeated_field_mask_val,json=repeatedFieldMaskVal,proto3" json:"repeated_field_mask_val,omitempty"`
	RepeatedEmptyVal       []*emptypb.Empty          `protobuf:"bytes,43,rep,name=repeated_empty_val,json=repeatedEmptyVal,proto3" json:"repeated_empty_val,omitempty"`
	// Map
	MapTimestampVal   map[string]*timestamppb.Timestamp  `protobuf:"bytes,51,rep,name=map_timestamp_val,json=mapTimestampVal,proto3" json:"map_timestamp_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapDurationVal    map[string]*durationpb.Duration    `protobuf:"bytes,52,rep,name=map_duration_val,json=mapDurationVal,proto3" json:"map_duration_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapBoolValueVal   map[string]*wrapperspb.BoolValue   `protobuf:"bytes,53,rep,name=map_bool_value_val,json=mapBoolValueVal,proto3" json:"map_bool_value_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringValueVal map[string]*wrapperspb.StringValue `protobuf:"bytes,54,rep,name=map_string_value_val,json=mapStringValueVal,proto3" json:"map_string_value_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapBytesValueVal  map[string]*wrapperspb.BytesValue  `protobuf:"bytes,55,rep,name=map_bytes_value_val,json=mapBytesValueVal,proto3" json:"map_bytes_value_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInt32ValueVal  map[string]*wrapperspb.Int32Value  `protobuf:"bytes,56,rep,name=map_int32_value_val,json=mapInt32ValueVal,proto3" json:"map_int32_value_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInt64ValueVal  map[string]*wrapperspb.Int64Value  `protobuf:"bytes,57,rep,name=map_int64_value_val,json=mapInt64ValueVal,proto3" json:"map_int64_value_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapUint32ValueVal map[string]*wrapperspb.UInt32Value `protobuf:"bytes,58,rep,name=map_uint32_value_val,json=mapUint32ValueVal,proto3" json:"map_uint32_value_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapUint64ValueVal map[string]*wrapperspb.UInt64Value `protobuf:"bytes,59,rep,name=map_uint64_value_val,json=mapUint64ValueVal,proto3" json:"map_uint64_value_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapFloatValueVal  map[string]*wrapperspb.FloatValue  `protobuf:"bytes,60,rep,name=map_float_value_val,json=mapFloatValueVal,proto3" json:"map_float_value_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapDoubleValueVal map[string]*wrapperspb.DoubleValue `protobuf:"bytes,61,rep,name=map_double_value_val,json=mapDoubleValueVal,proto3" json:"map_double_value_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapFieldMaskVal   map[string]*fieldmaskpb.FieldMask  `protobuf:"bytes,62,rep,name=map_field_mask_val,json=mapFieldMaskVal,proto3" json:"map_field_mask_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapEmptyVal       map[string]*emptypb.Empty          `protobuf:"bytes,63,rep,name=map_empty_val,json=mapEmptyVal,proto3" json:"map_empty_val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Oneof
	//
	// Types that are valid to be assigned to OneofVal:
	//
	//	*WellKnownTypes_OneofTimestampVal
	//	*WellKnownTypes_OneofDurationVal
	//	*WellKnownTypes_OneofBoolValueVal
	//	*WellKnownTypes_OneofStringValueVal
	//	*WellKnownTypes_OneofBytesValueVal
	//	*WellKnownTypes_OneofInt32ValueVal
	//	*WellKnownTypes_OneofInt64ValueVal
	//	*WellKnownTypes_OneofUint32ValueVal
	//	*WellKnownTypes_OneofUint64ValueVal
	//	*WellKnownTypes_OneofFloatValueVal
	//	*WellKnownTypes_OneofDoubleValueVal
	//	*WellKnownTypes_OneofFieldMaskVal
	//	*WellKnownTypes_OneofEmptyVal
	OneofVal isWellKnownTypes_OneofVal `protobuf_oneof:"oneof_val"`
	// Optional
	OptionalTimestampVal           *timestamppb.Timestamp `protobuf:"bytes,91,opt,name=optional_timestamp_val,json=optionalTimestampVal,proto3,oneof" json:"optional_timestamp_val,omitempty"`
	OptionalNotPresentTimestampVal *timestamppb.Timestamp `protobuf:"bytes,92,opt,name=optional_not_present_timestamp_val,json=optionalNotPresentTimestampVal,proto3,oneof" json:"optional_not_present_timestamp_val,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *WellKnownTypes) Reset() {
	*x = WellKnownTypes{}
	mi := &file_test_types_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WellKnownTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WellKnownTypes) ProtoMessage() {}

func (x *WellKnownTypes) ProtoReflect() protoreflect.Message {
	mi := &file_test_types_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WellKnownTypes.ProtoReflect.Descriptor instead.
func (*WellKnownTypes) Descriptor() ([]byte, []int) {
	return file_test_types_types_proto_rawDescGZIP(), []int{4}
}

func (x *WellKnownTypes) GetTimestampVal() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampVal
	}
	return nil
}

func (x *WellKnownTypes) GetDurationVal() *durationpb.Duration {
	if x != nil {
		return x.DurationVal
	}
	return nil
}

func (x *WellKnownTypes) GetBoolValueVal() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetStringValueVal() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetBytesValueVal() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetInt32ValueVal() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetInt64ValueVal() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetUint32ValueVal() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetUint64ValueVal() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetFloatValueVal() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetDoubleValueVal() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetFieldMaskVal() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMaskVal
	}
	return nil
}

func (x *WellKnownTypes) GetEmptyVal() *emptypb.Empty {
	if x != nil {
		return x.EmptyVal
	}
	return nil
}

func (x *WellKnownTypes) GetAnyVal() *anypb.Any {
	if x != nil {
		return x.AnyVal
	}
	return nil
}

func (x *WellKnownTypes) GetStructVal() *structpb.Struct {
	if x != nil {
		return x.StructVal
	}
	return nil
}

func (x *WellKnownTypes) GetValueVal() *structpb.Value {
	if x != nil {
		return x.ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetListValueVal() *structpb.ListValue {
	if x != nil {
		return x.ListValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetNotPresentTimestampVal() *timestamppb.Timestamp {
	if x != nil {
		return x.NotPresentTimestampVal
	}
	return nil
}

func (x *WellKnownTypes) GetNotPresentStringValueVal() *wrapperspb.StringValue {
	if x != nil {
		return x.NotPresentStringValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetNotPresentEmptyVal() *emptypb.Empty {
	if x != nil {
		return x.NotPresentEmptyVal
	}
	return nil
}

func (x *WellKnownTypes) GetMaskedTimestampVal() *timestamppb.Timestamp {
	if x != nil {
		return x.MaskedTimestampVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedTimestampVal() []*timestamppb.Timestamp {
	if x != nil {
		return x.RepeatedTimestampVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedDurationVal() []*durationpb.Duration {
	if x != nil {
		return x.RepeatedDurationVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedBoolValueVal() []*wrapperspb.BoolValue {
	if x != nil {
		return x.RepeatedBoolValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedStringValueVal() []*wrapperspb.StringValue {
	if x != nil {
		return x.RepeatedStringValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedBytesValueVal() []*wrapperspb.BytesValue {
	if x != nil {
		return x.RepeatedBytesValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedInt32ValueVal() []*wrapperspb.Int32Value {
	if x != nil {
		return x.RepeatedInt32ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedInt64ValueVal() []*wrapperspb.Int64Value {
	if x != nil {
		return x.RepeatedInt64ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedUint32ValueVal() []*wrapperspb.UInt32Value {
	if x != nil {
		return x.RepeatedUint32ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedUint64ValueVal() []*wrapperspb.UInt64Value {
	if x != nil {
		return x.RepeatedUint64ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedFloatValueVal() []*wrapperspb.FloatValue {
	if x != nil {
		return x.RepeatedFloatValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedDoubleValueVal() []*wrapperspb.DoubleValue {
	if x != nil {
		return x.RepeatedDoubleValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedFieldMaskVal() []*fieldmaskpb.FieldMask {
	if x != nil {
		return x.RepeatedFieldMaskVal
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedEmptyVal() []*emptypb.Empty {
	if x != nil {
		return x.RepeatedEmptyVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapTimestampVal() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.MapTimestampVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapDurationVal() map[string]*durationpb.Duration {
	if x != nil {
		return x.MapDurationVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapBoolValueVal() map[string]*wrapperspb.BoolValue {
	if x != nil {
		return x.MapBoolValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapStringValueVal() map[string]*wrapperspb.StringValue {
	if x != nil {
		return x.MapStringValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapBytesValueVal() map[string]*wrapperspb.BytesValue {
	if x != nil {
		return x.MapBytesValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapInt32ValueVal() map[string]*wrapperspb.Int32Value {
	if x != nil {
		return x.MapInt32ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapInt64ValueVal() map[string]*wrapperspb.Int64Value {
	if x != nil {
		return x.MapInt64ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapUint32ValueVal() map[string]*wrapperspb.UInt32Value {
	if x != nil {
		return x.MapUint32ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapUint64ValueVal() map[string]*wrapperspb.UInt64Value {
	if x != nil {
		return x.MapUint64ValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapFloatValueVal() map[string]*wrapperspb.FloatValue {
	if x != nil {
		return x.MapFloatValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapDoubleValueVal() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.MapDoubleValueVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapFieldMaskVal() map[string]*fieldmaskpb.FieldMask {
	if x != nil {
		return x.MapFieldMaskVal
	}
	return nil
}

func (x *WellKnownTypes) GetMapEmptyVal() map[string]*emptypb.Empty {
	if x != nil {
		return x.MapEmptyVal
	}
	return nil
}

func (x *WellKnownTypes) GetOneofVal() isWellKnownTypes_OneofVal {
	if x != nil {
		return x.OneofVal
	}
	return nil
}

func (x *WellKnownTypes) GetOneofTimestampVal() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofTimestampVal); ok {
			return x.OneofTimestampVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofDurationVal() *durationpb.Duration {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofDurationVal); ok {
			return x.OneofDurationVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofBoolValueVal() *wrapperspb.BoolValue {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofBoolValueVal); ok {
			return x.OneofBoolValueVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofStringValueVal() *wrapperspb.StringValue {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofStringValueVal); ok {
			return x.OneofStringValueVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofBytesValueVal() *wrapperspb.BytesValue {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofBytesValueVal); ok {
			return x.OneofBytesValueVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofInt32ValueVal() *wrapperspb.Int32Value {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofInt32ValueVal); ok {
			return x.OneofInt32ValueVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofInt64ValueVal() *wrapperspb.Int64Value {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofInt64ValueVal); ok {
			return x.OneofInt64ValueVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofUint32ValueVal() *wrapperspb.UInt32Value {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofUint32ValueVal); ok {
			return x.OneofUint32ValueVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofUint64ValueVal() *wrapperspb.UInt64Value {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofUint64ValueVal); ok {
			return x.OneofUint64ValueVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofFloatValueVal() *wrapperspb.FloatValue {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofFloatValueVal); ok {
			return x.OneofFloatValueVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofDoubleValueVal() *wrapperspb.DoubleValue {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofDoubleValueVal); ok {
			return x.OneofDoubleValueVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofFieldMaskVal() *fieldmaskpb.FieldMask {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofFieldMaskVal); ok {
			return x.OneofFieldMaskVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOneofEmptyVal() *emptypb.Empty {
	if x != nil {
		if x, ok := x.OneofVal.(*WellKnownTypes_OneofEmptyVal); ok {
			return x.OneofEmptyVal
		}
	}
	return nil
}

func (x *WellKnownTypes) GetOptionalTimestampVal() *timestamppb.Timestamp {
	if x != nil {
		return x.OptionalTimestampVal
	}
	return nil
}

func (x *WellKnownTypes) GetOptionalNotPresentTimestampVal() *timestamppb.Timestamp {
	if x != nil {
		return x.OptionalNotPresentTimestampVal
	}
	return nil
}

type isWellKnownTypes_OneofVal interface {
	isWellKnownTypes_OneofVal()
}

type WellKnownTypes_OneofTimestampVal struct {
	OneofTimestampVal *timestamppb.Timestamp `protobuf:"bytes,71,opt,name=oneof_timestamp_val,json=oneofTimestampVal,proto3,oneof"`
}

type WellKnownTypes_OneofDurationVal struct {
	OneofDurationVal *durationpb.Duration `protobuf:"bytes,72,opt,name=oneof_duration_val,json=oneofDurationVal,proto3,oneof"`
}

type WellKnownTypes_OneofBoolValueVal struct {
	OneofBoolValueVal *wrapperspb.BoolValue `protobuf:"bytes,73,opt,name=oneof_bool_value_val,json=oneofBoolValueVal,proto3,oneof"`
}

type WellKnownTypes_OneofStringValueVal struct {
	OneofStringValueVal *wrapperspb.StringValue `protobuf:"bytes,74,opt,name=oneof_string_value_val,json=oneofStringValueVal,proto3,oneof"`
}

type WellKnownTypes_OneofBytesValueVal struct {
	OneofBytesValueVal *wrapperspb.BytesValue `protobuf:"bytes,75,opt,name=oneof_bytes_value_val,json=oneofBytesValueVal,proto3,oneof"`
}

type WellKnownTypes_OneofInt32ValueVal struct {
	OneofInt32ValueVal *wrapperspb.Int32Value `protobuf:"bytes,76,opt,name=oneof_int32_value_val,json=oneofInt32ValueVal,proto3,oneof"`
}

type WellKnownTypes_OneofInt64ValueVal struct {
	OneofInt64ValueVal *wrapperspb.Int64Value `protobuf:"bytes,77,opt,name=oneof_int64_value_val,json=oneofInt64ValueVal,proto3,oneof"`
}

type WellKnownTypes_OneofUint32ValueVal struct {
	OneofUint32ValueVal *wrapperspb.UInt32Value `protobuf:"bytes,78,opt,name=oneof_uint32_value_val,json=oneofUint32ValueVal,proto3,oneof"`
}

type WellKnownTypes_OneofUint64ValueVal struct {
	OneofUint64ValueVal *wrapperspb.UInt64Value `protobuf:"bytes,79,opt,name=oneof_uint64_value_val,json=oneofUint64ValueVal,proto3,oneof"`
}

type WellKnownTypes_OneofFloatValueVal struct {
	OneofFloatValueVal *wrapperspb.FloatValue `protobuf:"bytes,80,opt,name=oneof_float_value_val,json=oneofFloatValueVal,proto3,oneof"`
}

type WellKnownTypes_OneofDoubleValueVal struct {
	OneofDoubleValueVal *wrapperspb.DoubleValue `protobuf:"bytes,81,opt,name=oneof_double_value_val,json=oneofDoubleValueVal,proto3,oneof"`
}

type WellKnownTypes_OneofFieldMaskVal struct {
	OneofFieldMaskVal *fieldmaskpb.FieldMask `protobuf:"bytes,82,opt,name=oneof_field_mask_val,json=oneofFieldMaskVal,proto3,oneof"`
}

type WellKnownTypes_OneofEmptyVal struct {
	OneofEmptyVal *emptypb.Empty `protobuf:"bytes,83,opt,name=oneof_empty_val,json=oneofEmptyVal,proto3,oneof"`
}

func (*WellKnownTypes_OneofTimestampVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofDurationVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofBoolValueVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofStringValueVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofBytesValueVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofInt32ValueVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofInt64ValueVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofUint32ValueVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofUint64ValueVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofFloatValueVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofDoubleValueVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofFieldMaskVal) isWellKnownTypes_OneofVal() {}

func (*WellKnownTypes_OneofEmptyVal) isWellKnownTypes_OneofVal() {}

// Nested Types
// https://developers.google.com/protocol-buffers/docs/proto#nested
type Types_NestedType struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NestedStringVal string                 `protobuf:"bytes,1,opt,name=nested_string_val,json=nestedStringVal,proto3" json:"nested_string_val,omitempty"`
	NestedSecretVal string                 `protobuf:"bytes,2,opt,name=nested_secret_val,json=nestedSecretVal,proto3" json:"nested_secret_val,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Types_NestedType) Reset() {
	*x = Types_NestedType{}
	mi := &file_test_types_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Types_NestedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Types_NestedType) ProtoMessage() {}

func (x *Types_NestedType) ProtoReflect() protoreflect.Message {
	mi := &file_test_types_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Types_NestedType.ProtoReflect.Descriptor instead.
func (*Types_NestedType) Descriptor() ([]byte, []int) {
	return file_test_types_types_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Types_NestedType) GetNestedStringVal() string {
	if x != nil {
		return x.NestedStringVal
	}
	return ""
}

func (x *Types_NestedType) GetNestedSecretVal() string {
	if x != nil {
		return x.NestedSecretVal
	}
	return ""
}

type OtherType2_NestedType struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NestedStringVal string                 `protobuf:"bytes,1,opt,name=nested_string_val,json=nestedStringVal,proto3" json:"nested_string_val,omitempty"`
	NestedSecretVal string                 `protobuf:"bytes,2,opt,name=nested_secret_val,json=nestedSecretVal,proto3" json:"nested_secret_val,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OtherType2_NestedType) Reset() {
	*x = OtherType2_NestedType{}
	mi := &file_test_types_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherType2_NestedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherType2_NestedType) ProtoMessage() {}

func (x *OtherType2_NestedType) ProtoReflect() protoreflect.Message {
	mi := &file_test_types_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherType2_NestedType.ProtoReflect.Descriptor instead.
func (*OtherType2_NestedType) Descriptor() ([]byte, []int) {
	return file_test_types_types_proto_rawDescGZIP(), []int{2, 0}
}

func (x *OtherType2_NestedType) GetNestedStringVal() string {
	if x != nil {
		return x.NestedStringVal
	}
	return ""
}

func (x *OtherType2_NestedType) GetNestedSecretVal() string {
	if x != nil {
		return x.NestedSecretVal
	}
	return ""
}

var File_test_types_types_proto protoreflect.FileDescriptor

const file_test_types_types_proto_rawDesc = "" +
	"\n" +
	"\x16test/types/types.proto\x12\x05types\x1a\x11marshal-zap.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\"\xfb\x12\n" +
	"\x05Types\x12#\n" +
	"\n" +
	"secret_val\x18\x01 \x01(\tB\x04\x88\xb5\x18\x01R\tsecretVal\x12$\n" +
	"\vsecret_val2\x18) \x01(\tB\x03\x80\x01\x01R\n" +
	"secretVal2\x12\x1d\n" +
	"\n" +
	"double_val\x18\x02 \x01(\x01R\tdoubleVal\x12\x1b\n" +
	"\tfloat_val\x18\x03 \x01(\x02R\bfloatVal\x12\x1b\n" +
	"\tint32_val\x18\x04 \x01(\x05R\bint32Val\x12\x1b\n" +
	"\tint64_val\x18\x05 \x01(\x03R\bint64Val\x12\x1d\n" +
	"\n" +
	"uint32_val\x18\x06 \x01(\rR\tuint32Val\x12\x1d\n" +
	"\n" +
	"uint64_val\x18\a \x01(\x04R\tuint64Val\x12\x1d\n" +
	"\n" +
	"sint32_val\x18\b \x01(\x11R\tsint32Val\x12\x1d\n" +
	"\n" +
	"sint64_val\x18\t \x01(\x12R\tsint64Val\x12\x1f\n" +
	"\vfixed32_val\x18\n" +
	" \x01(\aR\n" +
	"fixed32Val\x12\x1f\n" +
	"\vfixed64_val\x18\v \x01(\x06R\n" +
	"fixed64Val\x12!\n" +
	"\fsfixed32_val\x18\f \x01(\x0fR\vsfixed32Val\x12!\n" +
	"\fsfixed64_val\x18\r \x01(\x10R\vsfixed64Val\x12\x19\n" +
	"\bbool_val\x18\x0e \x01(\bR\aboolVal\x12\x1d\n" +
	"\n" +
	"string_val\x18\x0f \x01(\tR\tstringVal\x12\x1b\n" +
	"\tbytes_val\x18\x10 \x01(\fR\bbytesVal\x12,\n" +
	"\benum_val\x18\x11 \x01(\x0e2\x11.types.Types.EnumR\aenumVal\x127\n" +
	"\x0eother_type_val\x18\x12 \x01(\v2\x11.types.OtherType1R\fotherTypeVal\x12?\n" +
	"\x0fnested_type_val\x18\x13 \x01(\v2\x17.types.Types.NestedTypeR\rnestedTypeVal\x12X\n" +
	"\x1aother_type_nested_type_val\x18\x14 \x01(\v2\x1c.types.OtherType2.NestedTypeR\x16otherTypeNestedTypeVal\x12*\n" +
	"\x10oneof_string_val\x18\x15 \x01(\tH\x00R\x0eoneofStringVal\x12(\n" +
	"\x0foneof_int64_val\x18\x16 \x01(\x03H\x00R\roneofInt64Val\x12&\n" +
	"\x0eoneof_bool_val\x18\x17 \x01(\bH\x00R\foneofBoolVal\x124\n" +
	"\bmap_val1\x18\x18 \x03(\v2\x19.types.Types.MapVal1EntryR\amapVal1\x124\n" +
	"\bmap_val2\x18\x19 \x03(\v2\x19.types.Types.MapVal2EntryR\amapVal2\x12A\n" +
	"\rmap_empty_val\x18\x1a \x03(\v2\x1d.types.Types.MapEmptyValEntryR\vmapEmptyVal\x12#\n" +
	"\rrepeated_val1\x18\x1b \x03(\tR\frepeatedVal1\x126\n" +
	"\rrepeated_val2\x18\x1c \x03(\x0e2\x11.types.Types.EnumR\frepeatedVal2\x126\n" +
	"\rrepeated_val3\x18\x1d \x03(\v2\x11.types.OtherType1R\frepeatedVal3\x12,\n" +
	"\x12repeated_empty_val\x18\x1e \x03(\tR\x10repeatedEmptyVal\x126\n" +
	"\n" +
	"struct_val\x18\x1f \x01(\v2\x17.google.protobuf.StructR\tstructVal\x12\x17\n" +
	"\a_String\x18  \x01(\tR\x06String\x12&\n" +
	"\foptional_val\x18! \x01(\tH\x01R\voptionalVal\x88\x01\x01\x12<\n" +
	"\x18optional_not_present_val\x18\" \x01(\tH\x02R\x15optionalNotPresentVal\x88\x01\x01\x12;\n" +
	"\roptional_enum\x18# \x01(\x0e2\x11.types.Types.EnumH\x03R\foptionalEnum\x88\x01\x01\x12Q\n" +
	"\x19optional_not_present_enum\x18$ \x01(\x0e2\x11.types.Types.EnumH\x04R\x16optionalNotPresentEnum\x88\x01\x01\x12A\n" +
	"\x10optional_message\x18% \x01(\v2\x11.types.OtherType3H\x05R\x0foptionalMessage\x88\x01\x01\x12W\n" +
	"\x1coptional_not_present_message\x18& \x01(\v2\x11.types.OtherType3H\x06R\x19optionalNotPresentMessage\x88\x01\x01\x12:\n" +
	"\x0fpresent_message\x18' \x01(\v2\x11.types.OtherType3R\x0epresentMessage\x12A\n" +
	"\x13not_present_message\x18( \x01(\v2\x11.types.OtherType3R\x11notPresentMessage\x1aj\n" +
	"\n" +
	"NestedType\x12*\n" +
	"\x11nested_string_val\x18\x01 \x01(\tR\x0fnestedStringVal\x120\n" +
	"\x11nested_secret_val\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\x0fnestedSecretVal\x1a:\n" +
	"\fMapVal1Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aM\n" +
	"\fMapVal2Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.types.OtherType1R\x05value:\x028\x01\x1a>\n" +
	"\x10MapEmptyValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x04Enum\x12\n" +
	"\n" +
	"\x06ENUM_0\x10\x00\x12\n" +
	"\n" +
	"\x06ENUM_1\x10\x01\x12\n" +
	"\n" +
	"\x06ENUM_2\x10\x02B\v\n" +
	"\toneof_valB\x0f\n" +
	"\r_optional_valB\x1b\n" +
	"\x19_optional_not_present_valB\x10\n" +
	"\x0e_optional_enumB\x1c\n" +
	"\x1a_optional_not_present_enumB\x13\n" +
	"\x11_optional_messageB\x1f\n" +
	"\x1d_optional_not_present_message\"f\n" +
	"\n" +
	"OtherType1\x12(\n" +
	"\x10other_string_val\x18\x01 \x01(\tR\x0eotherStringVal\x12.\n" +
	"\x10other_secret_val\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\x0eotherSecretVal\"x\n" +
	"\n" +
	"OtherType2\x1aj\n" +
	"\n" +
	"NestedType\x12*\n" +
	"\x11nested_string_val\x18\x01 \x01(\tR\x0fnestedStringVal\x120\n" +
	"\x11nested_secret_val\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\x0fnestedSecretVal\"\x1e\n" +
	"\n" +
	"OtherType3\x12\x10\n" +
	"\x03val\x18\x01 \x01(\tR\x03val\"\xa41\n" +
	"\x0eWellKnownTypes\x12?\n" +
	"\rtimestamp_val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ftimestampVal\x12<\n" +
	"\fduration_val\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vdurationVal\x12@\n" +
	"\x0ebool_value_val\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\fboolValueVal\x12F\n" +
	"\x10string_value_val\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x0estringValueVal\x12C\n" +
	"\x0fbytes_value_val\x18\x05 \x01(\v2\x1b.google.protobuf.BytesValueR\rbytesValueVal\x12C\n" +
	"\x0fint32_value_val\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\rint32ValueVal\x12C\n" +
	"\x0fint64_value_val\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueR\rint64ValueVal\x12F\n" +
	"\x10uint32_value_val\x18\b \x01(\v2\x1c.google.protobuf.UInt32ValueR\x0euint32ValueVal\x12F\n" +
	"\x10uint64_value_val\x18\t \x01(\v2\x1c.google.protobuf.UInt64ValueR\x0euint64ValueVal\x12C\n" +
	"\x0ffloat_value_val\x18\n" +
	" \x01(\v2\x1b.google.protobuf.FloatValueR\rfloatValueVal\x12F\n" +
	"\x10double_value_val\x18\v \x01(\v2\x1c.google.protobuf.DoubleValueR\x0edoubleValueVal\x12@\n" +
	"\x0efield_mask_val\x18\f \x01(\v2\x1a.google.protobuf.FieldMaskR\ffieldMaskVal\x123\n" +
	"\tempty_val\x18\r \x01(\v2\x16.google.protobuf.EmptyR\bemptyVal\x12-\n" +
	"\aany_val\x18\x0e \x01(\v2\x14.google.protobuf.AnyR\x06anyVal\x126\n" +
	"\n" +
	"struct_val\x18\x0f \x01(\v2\x17.google.protobuf.StructR\tstructVal\x123\n" +
	"\tvalue_val\x18\x10 \x01(\v2\x16.google.protobuf.ValueR\bvalueVal\x12@\n" +
	"\x0elist_value_val\x18\x11 \x01(\v2\x1a.google.protobuf.ListValueR\flistValueVal\x12U\n" +
	"\x19not_present_timestamp_val\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\x16notPresentTimestampVal\x12\\\n" +
	"\x1cnot_present_string_value_val\x18\x13 \x01(\v2\x1c.google.protobuf.StringValueR\x18notPresentStringValueVal\x12I\n" +
	"\x15not_present_empty_val\x18\x14 \x01(\v2\x16.google.protobuf.EmptyR\x12notPresentEmptyVal\x12R\n" +
	"\x14masked_timestamp_val\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\x12maskedTimestampVal\x12P\n" +
	"\x16repeated_timestamp_val\x18\x1f \x03(\v2\x1a.google.protobuf.TimestampR\x14repeatedTimestampVal\x12M\n" +
	"\x15repeated_duration_val\x18  \x03(\v2\x19.google.protobuf.DurationR\x13repeatedDurationVal\x12Q\n" +
	"\x17repeated_bool_value_val\x18! \x03(\v2\x1a.google.protobuf.BoolValueR\x14repeatedBoolValueVal\x12W\n" +
	"\x19repeated_string_value_val\x18\" \x03(\v2\x1c.google.protobuf.StringValueR\x16repeatedStringValueVal\x12T\n" +
	"\x18repeated_bytes_value_val\x18# \x03(\v2\x1b.google.protobuf.BytesValueR\x15repeatedBytesValueVal\x12T\n" +
	"\x18repeated_int32_value_val\x18$ \x03(\v2\x1b.google.protobuf.Int32ValueR\x15repeatedInt32ValueVal\x12T\n" +
	"\x18repeated_int64_value_val\x18% \x03(\v2\x1b.google.protobuf.Int64ValueR\x15repeatedInt64ValueVal\x12W\n" +
	"\x19repeated_uint32_value_val\x18& \x03(\v2\x1c.google.protobuf.UInt32ValueR\x16repeatedUint32ValueVal\x12W\n" +
	"\x19repeated_uint64_value_val\x18' \x03(\v2\x1c.google.protobuf.UInt64ValueR\x16repeatedUint64ValueVal\x12T\n" +
	"\x18repeated_float_value_val\x18( \x03(\v2\x1b.google.protobuf.FloatValueR\x15repeatedFloatValueVal\x12W\n" +
	"\x19repeated_double_value_val\x18) \x03(\v2\x1c.google.protobuf.DoubleValueR\x16repeatedDoubleValueVal\x12Q\n" +
	"\x17repeated_field_mask_val\x18* \x03(\v2\x1a.google.protobuf.FieldMaskR\x14repeatedFieldMaskVal\x12D\n" +
	"\x12repeated_empty_val\x18+ \x03(\v2\x16.google.protobuf.EmptyR\x10repeatedEmptyVal\x12V\n" +
	"\x11map_timestamp_val\x183 \x03(\v2*.types.WellKnownTypes.MapTimestampValEntryR\x0fmapTimestampVal\x12S\n" +
	"\x10map_duration_val\x184 \x03(\v2).types.WellKnownTypes.MapDurationValEntryR\x0emapDurationVal\x12W\n" +
	"\x12map_bool_value_val\x185 \x03(\v2*.types.WellKnownTypes.MapBoolValueValEntryR\x0fmapBoolValueVal\x12]\n" +
	"\x14map_string_value_val\x186 \x03(\v2,.types.WellKnownTypes.MapStringValueValEntryR\x11mapStringValueVal\x12Z\n" +
	"\x13map_bytes_value_val\x187 \x03(\v2+.types.WellKnownTypes.MapBytesValueValEntryR\x10mapBytesValueVal\x12Z\n" +
	"\x13map_int32_value_val\x188 \x03(\v2+.types.WellKnownTypes.MapInt32ValueValEntryR\x10mapInt32ValueVal\x12Z\n" +
	"\x13map_int64_value_val\x189 \x03(\v2+.types.WellKnownTypes.MapInt64ValueValEntryR\x10mapInt64ValueVal\x12]\n" +
	"\x14map_uint32_value_val\x18: \x03(\v2,.types.WellKnownTypes.MapUint32ValueValEntryR\x11mapUint32ValueVal\x12]\n" +
	"\x14map_uint64_value_val\x18; \x03(\v2,.types.WellKnownTypes.MapUint64ValueValEntryR\x11mapUint64ValueVal\x12Z\n" +
	"\x13map_float_value_val\x18< \x03(\v2+.types.WellKnownTypes.MapFloatValueValEntryR\x10mapFloatValueVal\x12]\n" +
	"\x14map_double_value_val\x18= \x03(\v2,.types.WellKnownTypes.MapDoubleValueValEntryR\x11mapDoubleValueVal\x12W\n" +
	"\x12map_field_mask_val\x18> \x03(\v2*.types.WellKnownTypes.MapFieldMaskValEntryR\x0fmapFieldMaskVal\x12J\n" +
	"\rmap_empty_val\x18? \x03(\v2&.types.WellKnownTypes.MapEmptyValEntryR\vmapEmptyVal\x12L\n" +
	"\x13oneof_timestamp_val\x18G \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x11oneofTimestampVal\x12I\n" +
	"\x12oneof_duration_val\x18H \x01(\v2\x19.google.protobuf.DurationH\x00R\x10oneofDurationVal\x12M\n" +
	"\x14oneof_bool_value_val\x18I \x01(\v2\x1a.google.protobuf.BoolValueH\x00R\x11oneofBoolValueVal\x12S\n" +
	"\x16oneof_string_value_val\x18J \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x13oneofStringValueVal\x12P\n" +
	"\x15oneof_bytes_value_val\x18K \x01(\v2\x1b.google.protobuf.BytesValueH\x00R\x12oneofBytesValueVal\x12P\n" +
	"\x15oneof_int32_value_val\x18L \x01(\v2\x1b.google.protobuf.Int32ValueH\x00R\x12oneofInt32ValueVal\x12P\n" +
	"\x15oneof_int64_value_val\x18M \x01(\v2\x1b.google.protobuf.Int64ValueH\x00R\x12oneofInt64ValueVal\x12S\n" +
	"\x16oneof_uint32_value_val\x18N \x01(\v2\x1c.google.protobuf.UInt32ValueH\x00R\x13oneofUint32ValueVal\x12S\n" +
	"\x16oneof_uint64_value_val\x18O \x01(\v2\x1c.google.protobuf.UInt64ValueH\x00R\x13oneofUint64ValueVal\x12P\n" +
	"\x15oneof_float_value_val\x18P \x01(\v2\x1b.google.protobuf.FloatValueH\x00R\x12oneofFloatValueVal\x12S\n" +
	"\x16oneof_double_value_val\x18Q \x01(\v2\x1c.google.protobuf.DoubleValueH\x00R\x13oneofDoubleValueVal\x12M\n" +
	"\x14oneof_field_mask_val\x18R \x01(\v2\x1a.google.protobuf.FieldMaskH\x00R\x11oneofFieldMaskVal\x12@\n" +
	"\x0foneof_empty_val\x18S \x01(\v2\x16.google.protobuf.EmptyH\x00R\roneofEmptyVal\x12U\n" +
	"\x16optional_timestamp_val\x18[ \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x14optionalTimestampVal\x88\x01\x01\x12k\n" +
	"\"optional_not_present_timestamp_val\x18\\ \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x1eoptionalNotPresentTimestampVal\x88\x01\x01\x1a^\n" +
	"\x14MapTimestampValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\x1a\\\n" +
	"\x13MapDurationValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05value:\x028\x01\x1a^\n" +
	"\x14MapBoolValueValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\x05value:\x028\x01\x1ab\n" +
	"\x16MapStringValueValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05value:\x028\x01\x1a`\n" +
	"\x15MapBytesValueValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.BytesValueR\x05value:\x028\x01\x1a`\n" +
	"\x15MapInt32ValueValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05value:\x028\x01\x1a`\n" +
	"\x15MapInt64ValueValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05value:\x028\x01\x1ab\n" +
	"\x16MapUint32ValueValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x05value:\x028\x01\x1ab\n" +
	"\x16MapUint64ValueValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x05value:\x028\x01\x1a`\n" +
	"\x15MapFloatValueValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.FloatValueR\x05value:\x028\x01\x1ab\n" +
	"\x16MapDoubleValueValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1a^\n" +
	"\x14MapFieldMaskValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x05value:\x028\x01\x1aV\n" +
	"\x10MapEmptyValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.EmptyR\x05value:\x028\x01B\v\n" +
	"\toneof_valB\x19\n" +
	"\x17_optional_timestamp_valB%\n" +
	"#_optional_not_present_timestamp_valB<Z:github.com/kei2100/protoc-gen-marshal-zap/test/types;typesb\x06proto3"

var (
	file_test_types_types_proto_rawDescOnce sync.Once
	file_test_types_types_proto_rawDescData []byte
)

func file_test_types_types_proto_rawDescGZIP() []byte {
	file_test_types_types_proto_rawDescOnce.Do(func() {
		file_test_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_types_types_proto_rawDesc), len(file_test_types_types_proto_rawDesc)))
	})
	return file_test_types_types_proto_rawDescData
}

var file_test_types_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_test_types_types_proto_goTypes = []any{
	(Types_Enum)(0),                // 0: types.Types.Enum
	(*Types)(nil),                  // 1: types.Types
	(*OtherType1)(nil),             // 2: types.OtherType1
	(*OtherType2)(nil),             // 3: types.OtherType2
	(*OtherType3)(nil),             // 4: types.OtherType3
	(*WellKnownTypes)(nil),         // 5: types.WellKnownTypes
	(*Types_NestedType)(nil),       // 6: types.Types.NestedType
	nil,                            // 7: types.Types.MapVal1Entry
	nil,                            // 8: types.Types.MapVal2Entry
	nil,                            // 9: types.Types.MapEmptyValEntry
	(*OtherType2_NestedType)(nil),  // 10: types.OtherType2.NestedType
	nil,                            // 11: types.WellKnownTypes.MapTimestampValEntry
	nil,                            // 12: types.WellKnownTypes.MapDurationValEntry
	nil,                            // 13: types.WellKnownTypes.MapBoolValueValEntry
	nil,                            // 14: types.WellKnownTypes.MapStringValueValEntry
	nil,                            // 15: types.WellKnownTypes.MapBytesValueValEntry
	nil,                            // 16: types.WellKnownTypes.MapInt32ValueValEntry
	nil,                            // 17: types.WellKnownTypes.MapInt64ValueValEntry
	nil,                            // 18: types.WellKnownTypes.MapUint32ValueValEntry
	nil,                            // 19: types.WellKnownTypes.MapUint64ValueValEntry
	nil,                            // 20: types.WellKnownTypes.MapFloatValueValEntry
	nil,                            // 21: types.WellKnownTypes.MapDoubleValueValEntry
	nil,                            // 22: types.WellKnownTypes.MapFieldMaskValEntry
	nil,                            // 23: types.WellKnownTypes.MapEmptyValEntry
	(*structpb.Struct)(nil),        // 24: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 25: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 26: google.protobuf.Duration
	(*wrapperspb.BoolValue)(nil),   // 27: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 28: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 29: google.protobuf.BytesValue
	(*wrapperspb.Int32Value)(nil),  // 30: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 31: google.protobuf.Int64Value
	(*wrapperspb.UInt32Value)(nil), // 32: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 33: google.protobuf.UInt64Value
	(*wrapperspb.FloatValue)(nil),  // 34: google.protobuf.FloatValue
	(*wrapperspb.DoubleValue)(nil), // 35: google.protobuf.DoubleValue
	(*fieldmaskpb.FieldMask)(nil),  // 36: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),          // 37: google.protobuf.Empty
	(*anypb.Any)(nil),              // 38: google.protobuf.Any
	(*structpb.Value)(nil),         // 39: google.protobuf.Value
	(*structpb.ListValue)(nil),     // 40: google.protobuf.ListValue
}
var file_test_types_types_proto_depIdxs = []int32{
	0,  // 0: types.Types.enum_val:type_name -> types.Types.Enum
	2,  // 1: types.Types.other_type_val:type_name -> types.OtherType1
	6,  // 2: types.Types.nested_type_val:type_name -> types.Types.NestedType
	10, // 3: types.Types.other_type_nested_type_val:type_name -> types.OtherType2.NestedType
	7,  // 4: types.Types.map_val1:type_name -> types.Types.MapVal1Entry
	8,  // 5: types.Types.map_val2:type_name -> types.Types.MapVal2Entry
	9,  // 6: types.Types.map_empty_val:type_name -> types.Types.MapEmptyValEntry
	0,  // 7: types.Types.repeated_val2:type_name -> types.Types.Enum
	2,  // 8: types.Types.repeated_val3:type_name -> types.OtherType1
	24, // 9: types.Types.struct_val:type_name -> google.protobuf.Struct
	0,  // 10: types.Types.optional_enum:type_name -> types.Types.Enum
	0,  // 11: types.Types.optional_not_present_enum:type_name -> types.Types.Enum
	4,  // 12: types.Types.optional_message:type_name -> types.OtherType3
	4,  // 13: types.Types.optional_not_present_message:type_name -> types.OtherType3
	4,  // 14: types.Types.present_message:type_name -> types.OtherType3
	4,  // 15: types.Types.not_present_message:type_name -> types.OtherType3
	25, // 16: types.WellKnownTypes.timestamp_val:type_name -> google.protobuf.Timestamp
	26, // 17: types.WellKnownTypes.duration_val:type_name -> google.protobuf.Duration
	27, // 18: types.WellKnownTypes.bool_value_val:type_name -> google.protobuf.BoolValue
	28, // 19: types.WellKnownTypes.string_value_val:type_name -> google.protobuf.StringValue
	29, // 20: types.WellKnownTypes.bytes_value_val:type_name -> google.protobuf.BytesValue
	30, // 21: types.WellKnownTypes.int32_value_val:type_name -> google.protobuf.Int32Value
	31, // 22: types.WellKnownTypes.int64_value_val:type_name -> google.protobuf.Int64Value
	32, // 23: types.WellKnownTypes.uint32_value_val:type_name -> google.protobuf.UInt32Value
	33, // 24: types.WellKnownTypes.uint64_value_val:type_name -> google.protobuf.UInt64Value
	34, // 25: types.WellKnownTypes.float_value_val:type_name -> google.protobuf.FloatValue
	35, // 26: types.WellKnownTypes.double_value_val:type_name -> google.protobuf.DoubleValue
	36, // 27: types.WellKnownTypes.field_mask_val:type_name -> google.protobuf.FieldMask
	37, // 28: types.WellKnownTypes.empty_val:type_name -> google.protobuf.Empty
	38, // 29: types.WellKnownTypes.any_val:type_name -> google.protobuf.Any
	24, // 30: types.WellKnownTypes.struct_val:type_name -> google.protobuf.Struct
	39, // 31: types.WellKnownTypes.value_val:type_name -> google.protobuf.Value
	40, // 32: types.WellKnownTypes.list_value_val:type_name -> google.protobuf.ListValue
	25, // 33: types.WellKnownTypes.not_present_timestamp_val:type_name -> google.protobuf.Timestamp
	28, // 34: types.WellKnownTypes.not_present_string_value_val:type_name -> google.protobuf.StringValue
	37, // 35: types.WellKnownTypes.not_present_empty_val:type_name -> google.protobuf.Empty
	25, // 36: types.WellKnownTypes.masked_timestamp_val:type_name -> google.protobuf.Timestamp
	25, // 37: types.WellKnownTypes.repeated_timestamp_val:type_name -> google.protobuf.Timestamp
	26, // 38: types.WellKnownTypes.repeated_duration_val:type_name -> google.protobuf.Duration
	27, // 39: types.WellKnownTypes.repeated_bool_value_val:type_name -> google.protobuf.BoolValue
	28, // 40: types.WellKnownTypes.repeated_string_value_val:type_name -> google.protobuf.StringValue
	29, // 41: types.WellKnownTypes.repeated_bytes_value_val:type_name -> google.protobuf.BytesValue
	30, // 42: types.WellKnownTypes.repeated_int32_value_val:type_name -> google.protobuf.Int32Value
	31, // 43: types.WellKnownTypes.repeated_int64_value_val:type_name -> google.protobuf.Int64Value
	32, // 44: types.WellKnownTypes.repeated_uint32_value_val:type_name -> google.protobuf.UInt32Value
	33, // 45: types.WellKnownTypes.repeated_uint64_value_val:type_name -> google.protobuf.UInt64Value
	34, // 46: types.WellKnownTypes.repeated_float_value_val:type_name -> google.protobuf.FloatValue
	35, // 47: types.WellKnownTypes.repeated_double_value_val:type_name -> google.protobuf.DoubleValue
	36, // 48: types.WellKnownTypes.repeated_field_mask_val:type_name -> google.protobuf.FieldMask
	37, // 49: types.WellKnownTypes.repeated_empty_val:type_name -> google.protobuf.Empty
	11, // 50: types.WellKnownTypes.map_timestamp_val:type_name -> types.WellKnownTypes.MapTimestampValEntry
	12, // 51: types.WellKnownTypes.map_duration_val:type_name -> types.WellKnownTypes.MapDurationValEntry
	13, // 52: types.WellKnownTypes.map_bool_value_val:type_name -> types.WellKnownTypes.MapBoolValueValEntry
	14, // 53: types.WellKnownTypes.map_string_value_val:type_name -> types.WellKnownTypes.MapStringValueValEntry
	15, // 54: types.WellKnownTypes.map_bytes_value_val:type_name -> types.WellKnownTypes.MapBytesValueValEntry
	16, // 55: types.WellKnownTypes.map_int32_value_val:type_name -> types.WellKnownTypes.MapInt32ValueValEntry
	17, // 56: types.WellKnownTypes.map_int64_value_val:type_name -> types.WellKnownTypes.MapInt64ValueValEntry
	18, // 57: types.WellKnownTypes.map_uint32_value_val:type_name -> types.WellKnownTypes.MapUint32ValueValEntry
	19, // 58: types.WellKnownTypes.map_uint64_value_val:type_name -> types.WellKnownTypes.MapUint64ValueValEntry
	20, // 59: types.WellKnownTypes.map_float_value_val:type_name -> types.WellKnownTypes.MapFloatValueValEntry
	21, // 60: types.WellKnownTypes.map_double_value_val:type_name -> types.WellKnownTypes.MapDoubleValueValEntry
	22, // 61: types.WellKnownTypes.map_field_mask_val:type_name -> types.WellKnownTypes.MapFieldMaskValEntry
	23, // 62: types.WellKnownTypes.map_empty_val:type_name -> types.WellKnownTypes.MapEmptyValEntry
	25, // 63: types.WellKnownTypes.oneof_timestamp_val:type_name -> google.protobuf.Timestamp
	26, // 64: types.WellKnownTypes.oneof_duration_val:type_name -> google.protobuf.Duration
	27, // 65: types.WellKnownTypes.oneof_bool_value_val:type_name -> google.protobuf.BoolValue
	28, // 66: types.WellKnownTypes.oneof_string_value_val:type_name -> google.protobuf.StringValue
	29, // 67: types.WellKnownTypes.oneof_bytes_value_val:type_name -> google.protobuf.BytesValue
	30, // 68: types.WellKnownTypes.oneof_int32_value_val:type_name -> google.protobuf.Int32Value
	31, // 69: types.WellKnownTypes.oneof_int64_value_val:type_name -> google.protobuf.Int64Value
	32, // 70: types.WellKnownTypes.oneof_uint32_value_val:type_name -> google.protobuf.UInt32Value
	33, // 71: types.WellKnownTypes.oneof_uint64_value_val:type_name -> google.protobuf.UInt64Value
	34, // 72: types.WellKnownTypes.oneof_float_value_val:type_name -> google.protobuf.FloatValue
	35, // 73: types.WellKnownTypes.oneof_double_value_val:type_name -> google.protobuf.DoubleValue
	36, // 74: types.WellKnownTypes.oneof_field_mask_val:type_name -> google.protobuf.FieldMask
	37, // 75: types.WellKnownTypes.oneof_empty_val:type_name -> google.protobuf.Empty
	25, // 76: types.WellKnownTypes.optional_timestamp_val:type_name -> google.protobuf.Timestamp
	25, // 77: types.WellKnownTypes.optional_not_present_timestamp_val:type_name -> google.protobuf.Timestamp
	2,  // 78: types.Types.MapVal2Entry.value:type_name -> types.OtherType1
	25, // 79: types.WellKnownTypes.MapTimestampValEntry.value:type_name -> google.protobuf.Timestamp
	26, // 80: types.WellKnownTypes.MapDurationValEntry.value:type_name -> google.protobuf.Duration
	27, // 81: types.WellKnownTypes.MapBoolValueValEntry.value:type_name -> google.protobuf.BoolValue
	28, // 82: types.WellKnownTypes.MapStringValueValEntry.value:type_name -> google.protobuf.StringValue
	29, // 83: types.WellKnownTypes.MapBytesValueValEntry.value:type_name -> google.protobuf.BytesValue
	30, // 84: types.WellKnownTypes.MapInt32ValueValEntry.value:type_name -> google.protobuf.Int32Value
	31, // 85: types.WellKnownTypes.MapInt64ValueValEntry.value:type_name -> google.protobuf.Int64Value
	32, // 86: types.WellKnownTypes.MapUint32ValueValEntry.value:type_name -> google.protobuf.UInt32Value
	33, // 87: types.WellKnownTypes.MapUint64ValueValEntry.value:type_name -> google.protobuf.UInt64Value
	34, // 88: types.WellKnownTypes.MapFloatValueValEntry.value:type_name -> google.protobuf.FloatValue
	35, // 89: types.WellKnownTypes.MapDoubleValueValEntry.value:type_name -> google.protobuf.DoubleValue
	36, // 90: types.WellKnownTypes.MapFieldMaskValEntry.value:type_name -> google.protobuf.FieldMask
	37, // 91: types.WellKnownTypes.MapEmptyValEntry.value:type_name -> google.protobuf.Empty
	92, // [92:92] is the sub-list for method output_type
	92, // [92:92] is the sub-list for method input_type
	92, // [92:92] is the sub-list for extension type_name
	92, // [92:92] is the sub-list for extension extendee
	0,  // [0:92] is the sub-list for field type_name
}

func init() { file_test_types_types_proto_init() }
func file_test_types_types_proto_init() {
	if File_test_types_types_proto != nil {
		return
	}
	file_test_types_types_proto_msgTypes[0].OneofWrappers = []any{
		(*Types_OneofStringVal)(nil),
		(*Types_OneofInt64Val)(nil),
		(*Types_OneofBoolVal)(nil),
	}
	file_test_types_types_proto_msgTypes[4].OneofWrappers = []any{
		(*WellKnownTypes_OneofTimestampVal)(nil),
		(*WellKnownTypes_OneofDurationVal)(nil),
		(*WellKnownTypes_OneofBoolValueVal)(nil),
		(*WellKnownTypes_OneofStringValueVal)(nil),
		(*WellKnownTypes_OneofBytesValueVal)(nil),
		(*WellKnownTypes_OneofInt32ValueVal)(nil),
		(*WellKnownTypes_OneofInt64ValueVal)(nil),
		(*WellKnownTypes_OneofUint32ValueVal)(nil),
		(*WellKnownTypes_OneofUint64ValueVal)(nil),
		(*WellKnownTypes_OneofFloatValueVal)(nil),
		(*WellKnownTypes_OneofDoubleValueVal)(nil),
		(*WellKnownTypes_OneofFieldMaskVal)(nil),
		(*WellKnownTypes_OneofEmptyVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_types_types_proto_rawDesc), len(file_test_types_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_types_types_proto_goTypes,
		DependencyIndexes: file_test_types_types_proto_depIdxs,
		EnumInfos:         file_test_types_types_proto_enumTypes,
		MessageInfos:      file_test_types_types_proto_msgTypes,
	}.Build()
	File_test_types_types_proto = out.File
	file_test_types_types_proto_goTypes = nil
	file_test_types_types_proto_depIdxs = nil
}
